### ISSUE TITLE
Combobox custom group label breaks a11y support

### ISSUE THREAD

**Issue by vnguyen94** [twilio-labs/paste#1030]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
Adding a custom group label to the Combobox component breaks its a11y support.

**To Reproduce**
1. Go to https://paste.twilio.design/components/combobox/#combobox-with-custom-group-label
2. Try searching something and then use your arrow keys to navigate through the options

**Expected behavior**
I should be able to navigate through the options using keyboard arrow keys

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 87.0.4280.88 (Official Build) (x86_64)

**Additional context**
N/A

**Comment by richbachman** [comment]
Hi @vnguyen94 we just merged a fix for this. Let us know if there are any other issues.

**Comment by vnguyen94** [comment]
Looks good @richbachman, thanks for the heads up!
