### ISSUE TITLE
Missing a period ".", the end of sentence. 

### ISSUE THREAD

**Issue by sang-yeo** [twilio-labs/paste#1055]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
It's not a bug but I found out that the Input component page error message and hint text examples are missing periods "."
**To Reproduce**
1. Go to https://paste.twilio.design/components/input/#input-with-add-ons-prefix-suffix-text-or-icons
**Expected behavior**
End of sentence, we should have a period

**Screenshots**
<img width="232" alt="Screen Shot 2020-12-18 at 9 14 09 AM" src="https://user-images.githubusercontent.com/67388401/102643547-494f0980-4114-11eb-858e-d996466a03ed.png">
<img width="301" alt="Screen Shot 2020-12-18 at 9 34 38 AM" src="https://user-images.githubusercontent.com/67388401/102643556-4d7b2700-4114-11eb-9973-0bb25e45aeca.png">

**Comment by serifluous** [comment]
Thanks, Sang! Will get this fix in soon.
