### ISSUE TITLE
Link from patterns to contribute page lands on 404 page

### ISSUE THREAD

**Issue by ozaytsev86** [twilio-labs/paste#1059]
Trying to navigate from the patterns page to contribute through the link in the last paragraph of the page it lands on the 404 page.

**To Reproduce**
1. Go to [https://paste.twilio.design/patterns/#prioritized-backlog-of-patterns](https://paste.twilio.design/patterns/#prioritized-backlog-of-patterns)
2. Scroll to the bottom of the section
3. Click on [contributing the pattern](https://paste.twilio.design/patterns/patterns/contribute) link
4. See 404 error page

**Expected behavior**
The user should be redirected to the (contribute page)[https://paste.twilio.design/patterns/contribute]

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
 - Browser [chrome]
 - Version [87.0.4280.88 (Official Build) (64-bit)]

**Additional context**
It is happening because of the double /pattern in the URL -> (https://paste.twilio.design/patterns/patterns/contribute)

**Comment by richbachman** [comment]
Hi @ozaytsev86. Thanks for catching this. We'll get it fixed as soon as we can.

**Comment by TheSisb** [comment]
I believe this is fixed now, please re-open if still an issue.
