### ISSUE TITLE
Explaining Do's and Don'ts so that it's quick to grok

### ISSUE THREAD

**Issue by JT1989** [twilio-labs/paste#109]
**Problem:**
It takes quite a bit of time to grok what you shouldn't do and don't do with certain components. I'm here to quickly scan and digest information. I don't have time to read every word. 

1. The visual aids don't provide visual cues on whether it's a Do or a Don't. I can tell the design is _trying to_, but it can be stronger to provide more clarity
2. The visual aids don't address common "Don't do this"
3. The language that's used for the "Don't" can be a bit confusing. 

See below:

<img width="890" alt="Screen Shot 2019-09-27 at 12 02 09 PM" src="https://user-images.githubusercontent.com/8630856/65795396-05db3a80-e11f-11e9-9aba-097221ea455a.png">

Here's an example of a "Don't" - Within a command bar, folks are using a _Cancel anchor link_ when a _Cancel secondary button_  is more appropriate.
<img width="1439" alt="Screen Shot 2019-09-27 at 12 01 37 PM" src="https://user-images.githubusercontent.com/8630856/65795242-aaa94800-e11e-11e9-83d6-9e8fd00f3fd3.png">

**Suggestion #1 :**
Use real-world examples like this in our docs

**Example:**

For every do and don't - Don't tell us only with words. Show it with visual aids. I strongly recommend a 1:1 ratio of a Do/Don't to a visual aid. _Pictures can speak 1,000 words._
<img width="418" alt="Screen Shot 2019-09-27 at 12 11 08 PM" src="https://user-images.githubusercontent.com/8630856/65795837-0d4f1380-e120-11e9-94a7-0ac2f6b86de8.png">
<img width="718" alt="Screen Shot 2019-10-08 at 11 36 56 AM" src="https://user-images.githubusercontent.com/8630856/66423171-00ec7580-e9c0-11e9-9060-687d410e879d.png">

**Suggestion #2:**
Be precise with your words, language and grammar. 

**Example:**
Trying to understand what this means: _Don’t use an icon in place of or with anchor text._
Not sure what you are trying to communicate. It reads as an issue with grammar.

**Comment by serifluous** [comment]
Thanks, JT! Added to our backlog

**Comment by TheSisb** [comment]
Closing this because:
1) This is a practice we now are mindful of in ongoing work
2) The specific issue called out was resolved.  

If you find other cases, please file a new ticket.  Thank you!
