### ISSUE TITLE
@twilio-paste/toast with console

### ISSUE THREAD

**Issue by epardosanllorente** [twilio-labs/paste#1121]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
Toast component is been hide by Twilio console navbar (header).

**To Reproduce**
The project where this is happening is on Pilot and you will need to enable some flags but in reality, this looks like something that can be reproduced in any console project using the toast component. 
1. Go to Console (not using the console beta version)
2. Open a toast
3. The toast is been displayed under the navbar of console

**Expected behavior**
Would expect that toast will be overlapping any content on the page

**Screenshots**
Current behavior
![image](https://user-images.githubusercontent.com/75471026/106155304-d019ec00-6180-11eb-83b8-e39744d12ce4.png)
Expected behavior
![image](https://user-images.githubusercontent.com/75471026/106155443-fa6ba980-6180-11eb-9202-4513c889cf7f.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser : Chrome
 - Version 87.0.4280.141

**Additional context**
Apparently the toast has an z-index set to 90 and the nav of console to 1050.

**Comment by SiTaggart** [comment]
@epardosanllorente For now we've raised a ticket on Console to try and see if they can _reduce_ the zIndex of console masthead as it's set so high.

We'll get back to you when we hear back.

**Comment by TheSisb** [comment]
Console ticket: https://issues.corp.twilio.com/browse/CON-6494

**Comment by epardosanllorente** [comment]
> @epardosanllorente For now we've raised a ticket on Console to try and see if they can _reduce_ the zIndex of console masthead as it's set so high.
> 
> We'll get back to you when we hear back.

**Comment by epardosanllorente** [comment]
> @epardosanllorente For now we've raised a ticket on Console to try and see if they can _reduce_ the zIndex of console masthead as it's set so high.
> 
> We'll get back to you when we hear back.

thanks

**Comment by TheSisb** [comment]
Hi @epardosanllorente, 

We just merged a fix that will solve your z-index issues. Please pass the `__console_patch` boolean prop to either Toaster or ToastContainer, as per the docs: https://paste.twilio.design/components/toast#toaster-props
This will hardcode a higher z-index into our Toasts to make it appear over the masthead.

Let me know if you encounter any other issues.
