### ISSUE TITLE
Tooltip requires ref forwarding for components but is not documented.

### ISSUE THREAD

**Issue by GiantRobots** [twilio-labs/paste#1141]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
When using the tooltip with functional components you cannot use a component that does not forward refs. This is likely intentional behavior but it is unexpected because it is not documented.

**To Reproduce**
```typescript
const MyFuncComponent: React.FC = ({ children }) => <>{children}</>;

<Tooltip text="Black Lives Matter. We stand with the Black community.">
  <MyFuncComponent>
     <InformationIcon decorative={false} title="Information" />
   </MyFuncComponent>
</Tooltip>
```

![Screen Shot 2021-01-29 at 5 11 59 PM](https://user-images.githubusercontent.com/1903839/106339866-1b9dca00-6255-11eb-82a7-2451c35aa96d.png)

** Resolution **
Probably just update the docs and let people know that it's a requirement that the element be focusable and the child needs to forward refs to the actual Element

**Comment by SiTaggart** [comment]
This is good to note for when we get to actually writing proper documentation for the tooltip, thanks.

We currently only point out that the child [must be focusable](https://paste.twilio.design/components/tooltip#focusable-element), but the fact it must forward refs also, is a bit of an oversight.

We'll add this to the docs in the coming sprints.

**Comment by GiantRobots** [comment]
Yeah the focusable was good but a bit of a goose chase for why the tooltip wasn't showing up. 

I had some other weird edge cases for positioning but I wasn't paying much attention just trying to fix stuff. I might add on a few more edge cases, but I worry that the waters may be polluted because it's working with SendGrid CSS at the same time.

**Comment by GiantRobots** [comment]
Can we get a link to the Ticket that is tracking this work?

**Comment by SiTaggart** [comment]
In terms of updating the docs of tooltip, the ticket lives here https://issues.corp.twilio.com/browse/DSYS-1928

**Comment by TheSisb** [comment]
Fixed in https://github.com/twilio-labs/paste/pull/1303
