### ISSUE TITLE
@twilio-paste/modal padding-top: 0px overrides padding for console top nav bar

### ISSUE THREAD

**Issue by mirjammalksoo** [twilio-labs/paste#1149]
**Describe the bug**

The following behaviour mainly affects modals in current/old console (not beta version): 

Opening a modal adds `padding-top: 0px` to the `<body>` which overrides its initial `padding-top` and thus causes the side bar and page content to lose the top padding and move upwards under the top nav bar.

**To Reproduce**

For new or some recently developed projects/pages in (old) console (e.g. Admin Center) this bug occurs by default for all modals.

This bug is fixed in some existing projects with a global padding style to override the modal's `padding-top: 0`:

For example - fixed for modal which is shown when navigating to Programmable Messaging -> Try it Out -> Try WhatsApp:

![image](https://user-images.githubusercontent.com/40227184/106620870-aeeb3e00-657a-11eb-82c6-b24f59bb89af.png)

![image](https://user-images.githubusercontent.com/40227184/106619126-ed7ff900-6578-11eb-8b01-00e30df5e737.png)

Without the global style the modal view would look like this:

![image](https://user-images.githubusercontent.com/40227184/106620795-97ac5080-657a-11eb-8fef-bef13ba4e1e4.png)

**Expected behavior**

Opening a modal shouldn't add a `padding-top: 0` by default to the `body` (could be a parameter for example).

**Screenshots**

Page without modal:

![image](https://user-images.githubusercontent.com/40227184/106572043-98c08c00-6540-11eb-92c3-a59f0e0ddd9a.png)

Page with modal where page's top content is hidden under the top nav bar: 

![image](https://user-images.githubusercontent.com/40227184/106622028-d55da900-657b-11eb-99e7-b33ebdd2927e.png)

![image](https://user-images.githubusercontent.com/40227184/106619992-d1308c00-6579-11eb-91c0-1b1642bb3ca9.png)
![image](https://user-images.githubusercontent.com/40227184/106575486-d0313780-6544-11eb-9ea7-7e63b7acb635.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome
 - Version: 88.0.4324.96

**Additional context**

In the new console (beta version), there is an additional padding added to the body which by default overrides the `padding-top: 0px` and therefore currently fixes the issue:

![image](https://user-images.githubusercontent.com/40227184/106622773-9da33100-657c-11eb-9f1c-e8f953f89564.png)

**Comment by SiTaggart** [comment]
Hi @mirjammalksoo, are you currently using the `__console_patch` prop on the Modal component? https://paste.twilio.design/components/modal#modal-props

**Comment by mirjammalksoo** [comment]
Hi @SiTaggart! 

Currently not but I tested it out with the current/old console and the prop fixes the bug. Thanks! I somehow missed that prop when going through the docs and current solutions. 

However I am thinking if this solution is applicable also to the new console navigation (beta version), because stargate already provides a correct padding to the body and thus the margin-top would not be necessary (if I understand it correctly). 

The reason why I am asking is that the pages we are currently developing can be used with both old and new console, so the solution for this bug would have to be applicable for both of them.

Do you have any thoughts on this topic? Feel free to let me know if I misunderstood something :)

**Comment by SiTaggart** [comment]
In the long run this shouldn't be a problem. 

If you migrate your app to the new Console you should be living in their new context, so there is no injection of styles from stargate.

If you are living in the iframe, I was under the impression there was a flag available to turn off the injected (or some injected) styles from stargate. (If not the patch props is there for until you migrate the app to the new architecture)

**Comment by mirjammalksoo** [comment]
Understood, thank you for clarifying!

I'll close this issue as the patch prop will solve the issue for now.
