### ISSUE TITLE
Illustration Repo link permission denied

### ISSUE THREAD

**Issue by myfancypants** [twilio-labs/paste#1182]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
![image](https://user-images.githubusercontent.com/11448979/107555901-938cbe00-6b8c-11eb-94a2-ed8b1688e700.png)
The link for `Browse the illustration repository` https://library.twilio.com/web/2f44a10496e4c83b/shared-illustrations/ returns permission denied

**To Reproduce**
1. Go to https://paste.twilio.design/illustrations
2. Click on `Browse the illustration repository`
3. See permission denied

**Expected behavior**
I can access the link
reenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macos catalina
 - Browser chrome
 - Version 88

**Comment by JT1989** [comment]
Experiencing the same bug, using the same steps to reproduce and same desktop configuration:

<img width="724" alt="Screenshot 2021-02-10 at 17 50 01" src="https://user-images.githubusercontent.com/8630856/107563174-97710e00-6b95-11eb-9131-3719666ee9c6.png">

**Comment by serifluous** [comment]
@myfancypants @JT1989 It looks like the Brand team changed access controls to the illustration library. You'll have to go through IT and request access to "The Library (Bynder)". We'll update the instructions on the Paste site.

**Comment by JT1989** [comment]
Thanks Sarah :)
