### ISSUE TITLE
Principles nested in Getting Started section

### ISSUE THREAD

**Issue by sgbj** [twilio-labs/paste#119]
This is the behavior that I'm seeing on the website sidebar navigation. It looks like this is because the Principles nav item is nested inside the Getting Started nav item so the expanded nav items look disconnected. Is this intentional or is it supposed to come after?

![sidebar](https://user-images.githubusercontent.com/5178445/66238993-625dcd00-e6be-11e9-82d2-f63a727ea31f.gif)

If it's not intentional, can I submit a PR to fix it?

**Comment by SiTaggart** [comment]
Yeah, that's a bug. If you want to submit a PR, we'd love to see it.

**Comment by SiTaggart** [comment]
Thanks @sgbj
