### ISSUE TITLE
Broken link on Menu docs page

### ISSUE THREAD

**Issue by negomi** [twilio-labs/paste#1199]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
Link to the Button section is incorrect.

**To Reproduce**
1. Go to https://paste.twilio.design/components/menu/#choosing-a-menu-trigger
2. Click on Button link
3. See 404 page (Goes to https://paste.twilio.design/component/button, should be https://paste.twilio.design/components/button)

**Comment by serifluous** [comment]
@negomi thanks for the catch!

**Comment by richbachman** [comment]
Hi @negomi 
We just deployed a fix for the broken link. Thanks again for catching that one.
