### ISSUE TITLE
Missing CODE_OF_CONDUCT.MD

### ISSUE THREAD

**Issue by sidhyatikku** [twilio-labs/paste#143]
## Description

Most repos have a `CODE_OF_CONDUCT.MD` and is missing from this repo. I can copy-paste the copy paste the Code of Conduct files from other Twilio repos or a twilio personnel can make one.

**Comment by TheSisb** [comment]
Good catch!  If you have some time, mind adding a little section like on this repo https://github.com/twilio-labs/svg-to-react#code-of-conduct?

**Comment by sidhyatikku** [comment]
@TheSisb on it

**Comment by TheSisb** [comment]
Merged.  Thanks!
