### ISSUE TITLE
Combobox does not value "required" attribute

### ISSUE THREAD

**Issue by ycao2020** [twilio-labs/paste#1472]
After adding that attribute on Combobox and then checking on UI, the input field rendered does not have required. Is this intended? Trying to do a form validation, and found the required is missing.

**Comment by katieporter** [comment]
Hey @ycao2020 - thanks for raising this. We are looking into it and will get back to you shortly!

**Comment by richbachman** [comment]
Hi @ycao2020 We just merged the fix. The package deploy should go out in the next 24 hours.

**Comment by ycao2020** [comment]
@richbachman how do I get this change? do I need to upgrade my local Paste package or? my local has the same version as latest, 9.3.3.

**Comment by richbachman** [comment]
@ycao2020 you should see the change in core version 9.3.3. You may need to run a fresh yarn or npm install. Let me know if you're still having trouble after doing that.

**Comment by SiTaggart** [comment]
It'll go out in 9.3.4, we haven't merged the versioning PR yet https://github.com/twilio-labs/paste/pull/1480
