### ISSUE TITLE
Tooltip has weird icon when text is empty string

### ISSUE THREAD

**Issue by ycaoT** [twilio-labs/paste#1483]
I have a case where the text of Tooltip might be empty. However, when it's empty string, like "", it shows like the attached picture. It should not show/display anything if the text is empty. 
<img width="242" alt="Screen Shot 2021-05-24 at 5 07 12 PM" src="https://user-images.githubusercontent.com/61073239/119413266-e8bf8c00-bcb2-11eb-809a-b41a8b2426cb.png">

**Comment by TheSisb** [comment]
Hi @ycaoT, we try carefully to minimize logic within Paste components. For this particular instance, might we recommend you validate that you aren't passing an empty string to the Tooltip instead? I can't directly imagine a scenario where someone _would_ want an empty tooltip, so I'm a little torn on if this is a bug or not.
