### ISSUE TITLE
Empty states

### ISSUE THREAD

**Issue by frankfzhao** [twilio-labs/paste#1538]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
Some of the links for the empty state illustration is outdated

**To Reproduce**
1. Go to 'https://paste.twilio.design/patterns/empty-states'
2. Click on 'Download...' buttons for 1st, 3rd illustration
3. Page redirect to Bynder

**Expected behavior**
Correct link to Bynder to download the illustration

**Screenshots**
<img width="1767" alt="Screen Shot 2021-06-08 at 1 26 30 PM" src="https://user-images.githubusercontent.com/82524550/121245395-37e1f100-c85d-11eb-915c-47871c01f814.png">

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [chrome]

**Additional context**

**Comment by serifluous** [comment]
Thanks @frankfzhao ! A few questions:

1. Have you already requested access to Bynder through ServiceNow?
2. If you have, can you try the links again? I made some permissions on the assets and the collection less restrictive, but I'm not 100% sure if that fixes the issue.

**Comment by frankfzhao** [comment]
Hey Sarah, I have the access to Bynder. And I think it works now. Thanks for the quick fix!
