### ISSUE TITLE
Toasts appear to be broken?

### ISSUE THREAD

**Issue by sebm** [twilio-labs/paste#1542]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
Toasts are not … toasting … 🍞 

**To Reproduce**
https://paste.twilio.design/components/toast/#showing-dismissing-and-timing-out-a-toast
click "Add Toast"

**Expected behavior**
Expect a toast to show up.

**Screenshots**
A toast does not show up.

**Desktop (please complete the following information):**
 - OS: os x 10.15.17
 - Browser: chrome + ff
 - Version: the latest

**Comment by richbachman** [comment]
Hi @sebm. We've been unable to reproduce this issue. Would you mind verifying on your end? Thanks!

**Comment by sebm** [comment]
https://user-images.githubusercontent.com/188161/121573258-0ac74700-c9f3-11eb-8efc-4f21638ca1e8.mov

here's a screencap

**Comment by sebm** [comment]
this is Chrome Version 91.0.4472.77 (Official Build) (x86_64) on OS 11.5 - i upgraded this morning

**Comment by sebm** [comment]
Tried in FF 90.0b5 (64-bit), Safari Version 14.1.1 (15611.2.7.1.6) - same deal in all browsers, with no error feedback.

Interestingly on the storybook, on the "[toast container](https://5e53448165911c0022e68c74-ffhmauvxwg.chromatic.com/?path=/story/components-toast--toast-container-story)" story I can successfully create a toast but on the "[toaster](https://5e53448165911c0022e68c74-ffhmauvxwg.chromatic.com/?path=/story/components-toast--toaster-story)" story I cannot.

**Comment by richbachman** [comment]
Thanks for the information. We think we found the issue, and will be fixing as soon as possible. We'll update this issue when done.

**Comment by sebm** [comment]
Cool thanks @richbachman!

**Comment by TheSisb** [comment]
PR up with a fix: https://github.com/twilio-labs/paste/pull/1557. Gonna try and merge it today.

**Comment by sebm** [comment]
Nice one, thanks @TheSisb . I'd completely forgotten that I'd set reduced motion on my mac.

**Comment by TheSisb** [comment]
I'm glad you forgot 💯  Helped us track this bug down! 🥇

**Comment by TheSisb** [comment]
Fix was released in the latest version.
