### ISSUE TITLE
Consider using vertical three-dots icon for "more actions"

### ISSUE THREAD

**Issue by alejandro415** [twilio-labs/paste#163]
Because Sendgrid is using the vertical dots for the 'More actions' affordance, and because Material HIG recommends the vertical configuration for web, I wanted to suggest that we use the vertical form as well.

Referring to usage here (but may be in other places too):
https://share.goabstract.com/d40934f2-b02a-45c7-af53-b37c2d189487?mode=design&sha=9ada15ead068389a4b4bcda1562880622dbf97dd

**Comment by johannaweintraub** [comment]
I support this request and have 8 usability tests to show how intuitive it is as a pattern. Happy to share the videos if that would be useful in evaluating.

**Comment by aayushpi** [comment]
For clarity, are you looking for a vertical three dots pattern as an icon, or the menu component that is exposed when you click on it?

**Comment by johannaweintraub** [comment]
I'm looking for the icon...I assume the menu will use the same component as other menus

**Comment by serifluous** [comment]
> I support this request and have 7 usability tests to show how intuitive it is as a pattern. Happy to share the videos if that would be useful in evaluating.

@johannaweintraub Did you test the vertical against the horizontal format? Or just the vertical format?

**Comment by johannaweintraub** [comment]
I tested vertical only

**Comment by aayushpi** [comment]
To be a thorough test, you should be testing against a control. In this case it’s a generally accepted pattern, and since you’re just asking for an icon, I’m not opposed. However, any usability tests where were not tracking control variations may be suspect. I’ll tag Chad or Shavika on this later.

**Comment by johannaweintraub** [comment]
Yes, fair. I don't disagree on that point. For this case, I appreciate your acceptance of my research since like you said, it is a generally accepted pattern and 7 of 7 users found it without hesitation.

**Comment by aayushpi** [comment]
@serifluous Can you add a ticket to the backlog to add this icon to our system and then close this ticket out?

**Comment by serifluous** [comment]
Added to the backlog 👍
