### ISSUE TITLE
changelog shows Paste as 1.1 after a breaking change was made

### ISSUE THREAD

**Issue by aayushpi** [twilio-labs/paste#170]
We may want to unpublish or clarify the changelog intent to ensure that folks don't have version confusion.

**Comment by SiTaggart** [comment]
So, this https://paste.twilio.design/changelog changelog is _just_ the websites changelog as it's its own project and independently versioned from the whole mono repo. 

If it's meant to be a changelog for _everything_ then it needs a lot more work to include all other Pase packages.

**Comment by aayushpi** [comment]
Do we need it?

**Comment by SiTaggart** [comment]
The Changelog page itself?

**Comment by aayushpi** [comment]
yes?

**Comment by SiTaggart** [comment]
OK, each package has its own changelog. I don't see the need to be honest. We can just remove it if you want

**Comment by aayushpi** [comment]
Cool. Let's kill the changelog.

**Comment by TheSisb** [comment]
Looks to be resolved now.
