### ISSUE TITLE
Links - need black or grey link as secondary

### ISSUE THREAD

**Issue by johannaweintraub** [twilio-labs/paste#171]
There is a need for secondary links, particualarly for pages with a lot of links, in order to show hierarchy of actions. Here is an example.

![R5d-noHierarchy](https://user-images.githubusercontent.com/6243878/68608384-979cce00-0467-11ea-9323-714e03609110.png)
![R5d](https://user-images.githubusercontent.com/6243878/68608386-98356480-0467-11ea-8bf5-47ec39d8227e.png)

**Comment by travisterwilligar** [comment]
Adding my thoughts here. I could go either way on this as I don't have a super strong preference. I'd say that in this context it might be clearer to link the title of each account which I believe would convey a stronger hierarchy and could make the secondary links unnecessary in this context.

**Comment by johannaweintraub** [comment]
What would the titles look like visually and on-hover if they were links?

**Comment by aayushpi** [comment]
It would be exactly the same but inherit any size and weight. So it will be a large, heading link.

**Comment by johannaweintraub** [comment]
So blue heading with an underline on hover?

**Comment by aayushpi** [comment]
https://paste.twilio.design/components/anchor this in console + bigger

**Comment by serifluous** [comment]
Closing this since it's been resolved with the anchor on the heading. Thanks all for the discussion!
