### ISSUE TITLE
Keyboard accessibility in menu component

### ISSUE THREAD

**Issue by jweintraub** [twilio-labs/paste#1825]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
Keyboard accessibility issue with menus

**To Reproduce**
1. Go to 'https://paste.twilio.design/components/menu'
2. Use keyboard to tab to menu component on
3. Click 'enter' to open menu
4. Use keys to focus menu items
5. Click 'shift-tab' to refoc the main menu button component
6. Click 'enter' 

**Expected behavior**
Menu should close 

**Screenshots**
see video attached

https://user-images.githubusercontent.com/13891347/131572073-d1c192a6-f1ab-4159-bc3a-c09687dedf79.mov

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [chrome]
 - Version [10.15.7 (19H1]

I discovered this after the menu was implemented in console and I was testing keyboard accessibility

**Comment by SiTaggart** [comment]
This is working as expected I'm afraid. 

The enter key and down arrow key always open the menu when focus is placed on the menu trigger. It doesn't act like a toggle.

To close the menu you must either press the escape key or blur focus from the "control" (the button and menu are technically a single control)

**Comment by jweintraub** [comment]
Ah, ok, thanks.

Johanna Weintraub
Staff, Product Designer
[image: twilio] <http://www.twilio.com/?utm_source=email_signature>
