### ISSUE TITLE
Sort utilities and components in release order:

### ISSUE THREAD

**Issue by aayushpi** [twilio-labs/paste#198]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

## Describe the functionality you're looking for

Currently, the component and utilities overview page list components in alphabetical order. While this is fine, it means that a few components that are ready to be used or tested may be buried amongst a sea of backlog components. I propose sorting components in the following order:

1. production
2. beta
3. alpha
4. backlog

**Comment by SiTaggart** [comment]
Currently the overview page on Components and Utilities are ordered in two groups

- Alpha, Beta, Production Components released on NPM (install able)
  - Ordered Alphabetically
- Backlog
  - Ordered Alphabetically

Right now the first group contains some components that are on NPM but lack docs and polish.

If all of the components in the top groups had docs, would that solve the problem?

**Comment by aayushpi** [comment]
I’d order the top group in terms of release, but yes m, if all components had docs this problem is mitigated.

I also wonder if we need some sort of color indicator for glanceable indications of components.

**Comment by TheSisb** [comment]
Hi @aayushpi, it sounds like your concern is around communicating new component releases.  I'm not sure we should alter the sorting of the table if that's the case, at least until we have tables with sort arrows in the header. We're currently brainstorming other strategies to communicate new releases that, hopefully, would reach a wider audience.

I'm going to close this ticket for now but please reach out if you have further questions or concerns.
