### ISSUE TITLE
Update Engineering Guidelines to highlight paste-core

### ISSUE THREAD

**Issue by aayushpi** [twilio-labs/paste#199]
In the [Engineering Guidelines](https://paste.twilio.design/getting-started/engineering/), the document says that `Currently, every package is standalone in the paste project. While this means you only get what you need, it makes it a little more tedious to get started. We hope to address this in the near future, but for now you can run:`

This is no longer true thanks to `paste-core`. Can we update the docs to reflect that?

**Comment by SiTaggart** [comment]
It's about time we revisited and updated the engineering getting started guide. I've added this to our backlog

**Comment by TheSisb** [comment]
This has been resolved in a recent update to those guidelines.
