### ISSUE TITLE
Request To Improve Installation/Init DX

### ISSUE THREAD

**Issue by hharnisc** [twilio-labs/paste#203]
**Describe the bug**
Filing this as a bug since I don't want to offer up a singular solution to this problem (since there are many with different trade offs!). It's more of a request for an enhancement to the DX.

I'd like to request we offer an easy default to get going with Paste components. Right now we need to install quite a few dependencies to get going with Paste. While the easy way would be the default, It would be great to still have a way to manage the dependencies individually (escape hatch!)

**To Reproduce**
1. yarn add @twilio-paste/button (got this from https://paste.twilio.design/components/button)
2. miss the peerDependency warning
3. Install all the dependencies manually
4. Have to maintain all the dependencies manually forever

**Expected behavior**
Install one dependency, start building!

**Additional context**

I started installing just the Button, and missed the peerDependency warnings because there are hundreds in the project I'm working with. I've seen several applications in the same state so this seems like it would happen again.

Some ideas:
- Meta package that can bulk install dependencies (the create react app approach)
- Bake the dependencies (other than things like react) into `core`

**Comment by TheSisb** [comment]
Sorry for the delayed response to this issue.  This is something we're still evaluating.  As of now, we know there are many peerDeps and that it's slightly tedious for the init dx.  We plan to give this issue more thought moving into 2020.  I'll make sure to update this issue with our plans.

**Comment by TheSisb** [comment]
A late but needed update:
- We've added a package called `@twilio-paste/core` if you just want to get all the components in one go.
- We moved several third party deps into paste wrapper packages to better manage those deps. In the case of emotion and styled-system, that also brought down 5 needed deps to 1.

We have plans to add a `@twilio-paste/libraries` or something similar to `core` to bundle in the still individually installed parts.

**Comment by hharnisc** [comment]
Thank you for the update @TheSisb 🙌 happy to give this a try when you're looking for early test cases!

**Comment by TheSisb** [comment]
`@twilio-paste/core` now includes everything except for the `@twilio-paste/icons` package in an unbarreled fashion. 
After v3.0.1 of core, you can do `import {Theme} from '@twilio-paste/core/theme'. See [this codesandbox for more import examples](https://codesandbox.io/s/swapping-themes-o811i?file=/src/index.tsx)

Docs + announcement coming soon.  Going to mark this closed now! 😅
