### ISSUE TITLE
Color text warning and -strong are the same color

### ISSUE THREAD

**Issue by pamelahu** [twilio-labs/paste#2038]
Unsure if this was an intentional update... On the paste website and token that my engineer is using, the color-text-warning and color-text-warning-strong color are the same but in Figma it's different. Which one is correct?

<img width="798" alt="Screen Shot 2021-11-15 at 12 32 43 PM" src="https://user-images.githubusercontent.com/18605252/141828814-db8d5d1a-5300-4617-afb9-a762d94c32fc.png">

![Screen Shot 2021-11-15 at 12 44 19 PM](https://user-images.githubusercontent.com/18605252/141829224-9e9b8cd6-077f-4efb-93b7-373d9ac69b22.png)

Also, still kinda new to Twilio, not sure if this is the correct place to submit my issue? Or what the protocol is for submitting here vs. Slack vs. office hours?

**Comment by loreina** [comment]
Hi @pamelahu, thanks for catching this! `color-text-warning` should point to `palette-orange-70` and `color-text-warning-strong` should point to `palette-orange-80` in Default theme.

I made a PR to fix this and it should be out in our next release: #2054 

To answer your question about support, you're in the right place! This section in our doc site also explains the best support channel to reach us depending on the issue: https://paste.twilio.design/getting-started/working-guide#support-questions-feature-requests-bug-reports-and-updates

**Comment by loreina** [comment]
Hey @pamelahu, just an update: `color-text-warning` token pointing to `orange-70` doesn't pass our background contrast checks. Instead, we'll update Figma so `color-text-warning` points to `orange-80` (same as `color-text-warning-strong`) and revisit both tokens in the future.

Here's the Figma branch if you'd like to follow along on progress: https://www.figma.com/file/OZKRQFOkOAl413m5JVIYE6/branch/NgoIJaozGr3upa8KNIwrkV/Paste-Default-Theme

Thanks for your patience. The fix will be in very very soon! 🤞
