### ISSUE TITLE
MenuItem component with href doesn't work within DataGrid

### ISSUE THREAD

**Issue by jsheppard-twilio** [twilio-labs/paste#2061]
https://codesandbox.io/s/composable-cells-datagrid-forked-0w2yh?file=/src/App.tsx

**Describe the bug**
Menu component with href attribute on MenuItem doesn't work once the component is within the Datagrid component.
Menu opens and closes at normal, but when I click on an item with href nothing happens.

**To Reproduce**
https://codesandbox.io/s/composable-cells-datagrid-forked-0w2yh?file=/src/App.tsx
In this example I've simply added the href attribute to the Settings menu item.
The Menu has been added both inside and outside of the Datagrid component.
"Working Menu settings link" menu (outside Datagrid) - once clicked opens the url.
"Not working link" menu (inside Datagrid) - once clicked just closes the menu and doesn't open url.

**Expected behavior**
Adding href to MenuItem should open the given url when a user clicks on it.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by TheSisb** [comment]
The latest version of core (10.18.0) has the fix. Let us know if you encounter any other issues.
