### ISSUE TITLE
The TextArea is replaced with the `ce` component on deployment.

### ISSUE THREAD

**Issue by gkassym** [twilio-labs/paste#2206]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**

The TextArea works very well on dev, but when we deployed it was changed to `ce` component. Then Textarea was not clickable. So this issue was fixed by the patch. Why is this happening? Could you check?

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1175" alt="Screenshot 2022-02-10 at 10 58 40 AM" src="https://user-images.githubusercontent.com/95677319/153574974-7f95d38f-bc4d-4aa4-a534-9c58676823a2.png">

**Desktop (please complete the following information):**

**Additional context**

**Comment by shleewhite** [comment]
Hi @gkassym, thanks for reaching out to us about this!

Could you provide a minimal reproduction of it? We have not found this issue in our builds of Textarea.

**Comment by TheSisb** [comment]
Hello @gkassym, 

Did you manage to resolve this issue? I'm going to close it due to inactivity for now, however please report back if you have additional issues or information.
