### ISSUE TITLE
Spotted a documentation error on /customization/creating-a-custom-theme/

### ISSUE THREAD

**Issue by sang-yeo** [twilio-labs/paste#2241]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
Paste theme designer link returns 404 

**To Reproduce**
1. Go to '[...](https://paste.twilio.design/customization/creating-a-custom-theme/)'
2. Click on 'Paste Theme Designer link'
3. See error

**Additional context**
The link https://paste-theme-designer.netlify.app/edit needs to update

**Comment by nkrantz** [comment]
PR is closed, closing this Issue. Thanks @sang-yeo !
