### ISSUE TITLE
Copy Icon

### ISSUE THREAD

**Issue by hharnisc** [twilio-labs/paste#227]
## Is this related to an existing Paste Component? Please link it here:

No

## Describe the functionality you're looking for

The new design I'm working calls for a `copy` Icon and I'd like to use a Paste icon. Below is an example of general design of the `copy` Icon.

![image](https://user-images.githubusercontent.com/1388079/70752867-bd302800-1cf0-11ea-9e4a-f74b8579b7e9.png)

**Comment by serifluous** [comment]
Added to our backlog.

**Comment by TheSisb** [comment]
This has now been merged 🎉
