### ISSUE TITLE
Badge type error when passing an icon

### ISSUE THREAD

**Issue by dholliday3** [twilio-labs/paste#2292]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
When passing an icon to the Badge component getting a warning in the console about passing an incorrect prop. 

"Warning: Failed prop type: Invalid prop `children` supplied to `Badge`, expected one of type [string, string]." 

**To Reproduce**
1. Pass as icon as a child to the Badge component

**Expected behavior**
Expected to render properly without any warnings. 

**Screenshots**
<img width="650" alt="Screen Shot 2022-03-10 at 4 29 07 PM" src="https://user-images.githubusercontent.com/15958912/157778502-40324fdb-2a3f-4d64-a0bc-b06ae5cf602e.png">

<img width="670" alt="Screen Shot 2022-03-10 at 4 31 24 PM" src="https://user-images.githubusercontent.com/15958912/157778584-1901e177-c522-450a-95b5-aa5d78e55f5a.png">

**Desktop (please complete the following information):**

**Additional context**
Using React with Typescript.

**Comment by shleewhite** [comment]
Hi @dholliday3! 

What version of Paste Core are you using? I believe this has already been fixed in [@twilio-paste/core@11.0.0](https://github.com/twilio-labs/paste/releases/tag/%40twilio-paste%2Fcore%4011.0.0).

**Comment by dholliday3** [comment]
Ah, that must be it. We're still on 10.20.0.
