### ISSUE TITLE
Combobox starts behaving erratically in grouped options mode when passed options are not in sorted order

### ISSUE THREAD

**Issue by josamit** [twilio-labs/paste#2308]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
Combobox starts behaving erratically in grouped options mode when passed options are not in sorted order

**To Reproduce**
1. Go to 'https://paste.twilio.design/components/combobox/#combobox-with-option-groups'
2. Click on view code and **change combobox options in an unsorted order** similar to following screenshot.
<img width="788" alt="image" src="https://user-images.githubusercontent.com/62208722/159483525-ced75e86-4a1c-404a-a982-7898b7a3d02b.png">
3. Click on combobox now and scroll through options. **The options will start auto scrolling erratically** when you hover on the option menu from the bottom. More details in the screen-capture below:

![combobox_issue](https://user-images.githubusercontent.com/62208722/159483863-f1fa24aa-6ea5-4539-9cb5-07b1885f0396.gif)

**Expected behavior**
The scrolling behaviour should be consistent in both grouped and non group options. This bug request is coming from investigation of few of our customer escalations related to this. 

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version 8.1.1

**Additional context**

**Comment by shleewhite** [comment]
@josamit Just following up on this again, could you please provide more information on the customer escalation? Is it happening in their code or just on our website? Also, could you please send the Zendesk tickets? Thank you!

**Comment by josamit** [comment]
@shleewhite  Ticket : https://issues.corp.twilio.com/browse/COMPUI-126 Slack Thread : https://twilio.slack.com/archives/CSDLH7HG9/p1647326225977409

**Comment by andipants12** [comment]
@josamit Hello there 👋 We have a fix that is ready to be merged very soon. You can read more about the issue by checking out the linked PR above. I will reach out here and let you know when the fix is officially released. Please let us know if you have any questions or feedback in the meantime.

Thank you for taking the time to help up improve Paste! 🏅

**Comment by josamit** [comment]
@andipants12 thank you so very much, I will keep an eye out for the update on release 🙇

**Comment by TheSisb** [comment]
Hi @josamit,

The fix has been merged any will be deployed and available in the `@twilio-paste/core@11.5.0` version in a few minutes.
