### ISSUE TITLE
DatePicker typescript errors

### ISSUE THREAD

**Issue by nina-ye** [twilio-labs/paste#2318]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
I'm currently on Paste Core 10.15.0 but when I update to 10.18.0 or later, I get the following typescript errors for the DatePicker component
```
ERROR in ./node_modules/@twilio-paste/date-picker/dist/DatePicker.d.ts(4,76):
TS2344: Type '"hidden" | "size" | "style" | "element" | "multiple" | "disabled" | "form" | "slot" | "title" | "pattern" | "children" | "list" | "step" | "name" | "id" | "value" | "height" | "paddingRight" | ... 270 more ... | "enterKeyHint"' does not satisfy the constraint '"hidden" | "size" | "style" | "element" | "multiple" | "disabled" | "form" | "slot" | "title" | "pattern" | "children" | "list" | "step" | "type" | "name" | "id" | "value" | "height" | ... 272 more ... | "insertBefore"'.
  Type '"enterKeyHint"' is not assignable to type '"hidden" | "size" | "style" | "element" | "multiple" | "disabled" | "form" | "slot" | "title" | "pattern" | "children" | "list" | "step" | "type" | "name" | "id" | "value" | "height" | ... 272 more ... | "insertBefore"'.
```
```
ERROR in ./src/pages/SettingsIPAddresses/components/Filter/index.tsx(190,20):
TS2741: Property 'enterKeyHint' is missing in type '{ id: string; name: string; ref: { <TFieldElement extends FieldElement<FilterForm<T>>>(rules?: Partial<{ required: string | boolean | ValidationValueMessage<boolean>; ... 8 more ...; setValueAs: (value: any) => any; }> | undefined): (ref: (TFieldElement & HTMLInputElement) | ... 3 more ... | null) => void; (name: Fi...' but required in type 'Pick<InputProps, "hidden" | "size" | "style" | "element" | "multiple" | "disabled" | "form" | "slot" | "title" | "pattern" | "children" | "list" | "step" | "name" | "id" | ... 273 more ... | "enterKeyHint">'.
```

**To Reproduce**
1. Use the DatePicker on Paste Core 10.15.0
2. Update to 10.18.0 or later
3. See enterKeyHint TypeScript errors

**Expected behavior**
Expected to not get TypeScript errors so I can use the latest version of Paste's DatePicker

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by shleewhite** [comment]
Hi @nina-ye!

Thanks for posting this. Could you make a minimal reproduction of the bug in CodeSandbox, similar to this https://codesandbox.io/s/serverless-dew-suuxf8?file=/src/App.tsx? I tried, but was unable to reproduce the issue.

**Comment by nina-ye** [comment]
@shleewhite 
Thanks for looking into this! Here's a CodeSandbox - https://codesandbox.io/s/pensive-rain-x2w3f2?file=/src/App.tsx. I see the typescript error after adding  "@types/react": "^16.9.34" to the devDependencies

**Comment by SiTaggart** [comment]
This is because we set a dependency on `"@types/react": "^17.0.31"`, see here https://github.com/twilio-labs/paste/blob/bec53914b9d5baf25323f768b3b7522bd7755f43/packages/paste-types/package.json#L30

If you override our dependencies you'll likely be seeing a warning in you terminal when installing, and you will run into type mismatch issues.

Are you able to either update your react types package to match our requirement?

**Comment by nina-ye** [comment]
Thank you! We updated @types/react to 17 just recently so I tried updating Paste again and no longer seeing the issue
