### ISSUE TITLE
Input type="number" is not supported

### ISSUE THREAD

**Issue by kivanchuk** [twilio-labs/paste#2357]
Thanks for helping make Paste better! For general questions or feature requests, please post [a discussion](https://github.com/twilio-labs/paste/discussions/new).

**Describe the bug**
When I create Input component with type="number", the type is actually "text" in the generated component.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by TheSisb** [comment]
Hi @kivanchuk,

I'm going to close this as a dupe in favor of the ongoing discussion at https://github.com/twilio-labs/paste/discussions/2356.
