### ISSUE TITLE
Alert and Information Circle Icons

### ISSUE THREAD

**Issue by kateschwarz** [twilio-labs/paste#237]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

## Is this related to an existing Paste Component? Please link it here:
No

## Describe the functionality you're looking for
The new design I am working on requires an `Information Circle` and an `Alert Circle` depending on account status (Info for Trial and Alert for Suspended). Below are Streamline icons as an example of what I'm looking to add to our project.
![image](https://user-images.githubusercontent.com/54084724/71105380-b5520700-217a-11ea-9ee1-ee603e42fa69.png)
![image](https://user-images.githubusercontent.com/54084724/71105405-be42d880-217a-11ea-8fb1-f0ad0df5dda3.png)

**Comment by TheSisb** [comment]
Hey Kate! These icons are currently on our roadmap as part of the Alert component.  I'll try to get them in soon

**Comment by kateschwarz** [comment]
Awesome, thanks!

**Comment by TheSisb** [comment]
Merged the relevant Paste icons.  Will be doing a NPM deploy later today.
