### ISSUE TITLE
Spotted a documentation error on /introduction/for-engineers/manual-installation

### ISSUE THREAD

**Issue by brian-carlisle** [twilio-labs/paste#2392]
Thanks for helping make Paste better! For general questions or feature requests, please post [a discussion](https://github.com/twilio-labs/paste/discussions/new).

**Describe the bug**

"import {Theme} from '@twilio-paste/core/theme';
// Wrap your root component with the Theme.Provider like so:
const App = () => (
  <Theme.Provider theme="default">
    <RestOfYourAppInHere />
  </Theme.Provider>
);"

Twilio flex react plugins do not have this structure, where am I supposed to put this?

**Comment by andipants12** [comment]
Hi there @brian-carlisle 👋 Thanks for reaching out. Could you please provide some more information so we can assist?

Could you tell us:
1. Generally what it is you are trying to accomplish.
2. Reproduction steps (with source code, if possible!) where you experienced the bug.

Sounds like you might be wondering how to use the `Theme.Provider` in the flex plugin you are working on. If that is the case, and this is not in fact a regression or bug, could you please close this bug and [create a discussion instead](https://github.com/twilio-labs/paste/discussions/new)?

**Comment by nkrantz** [comment]
Hey @brian-carlisle - just checking in here. Were you able to figure out how to add the Theme Provider to your plugin? Let me know if there are any questions you still have! Otherwise I'll close this Issue.
