### ISSUE TITLE
Bundle Size Tracking

### ISSUE THREAD

**Issue by hharnisc** [twilio-labs/paste#240]
## Is this related to an existing Paste Component? Please link it here:

No

## Describe the functionality you're looking for
When building new components and adding new library it is not immediately obvious how they impact build size.  This is a request to add tooling to check the build size, report the diff from master (via github status) and fail the build if the bundle size gets over a prescribed threshold.

Here's a (widely used) tool that can accomplish the goal: https://github.com/siddharthkp/bundlesize

To setup the cool stuff you need write access to authorize the app 😄

**Comment by SiTaggart** [comment]
We have plans to show the package size on each component page as part of the top section, so this aligns pretty well. We'll at least have the data eventually.

We'd have to do it on a per component / package basis, on each PR. 

Does that align with what you're after?

**Comment by hharnisc** [comment]
@SiTaggart it does and then some 🎉

**Comment by SiTaggart** [comment]
hey @hharnisc would this https://github.com/twilio-labs/paste/issues/240 meet your request?

**Comment by hharnisc** [comment]
Definitely! Nice find on the GH Action 🙌
