### ISSUE TITLE
Paste 13: Property 'css' is missing in type...

### ISSUE THREAD

**Issue by george-cz** [twilio-labs/paste#2430]
**Describe the bug**
In Paste 13, some of the components now require a `css` prop to be passed. Without it, the TS fails to compile.
The affected components in our codebase are:

- FormPillGroup
- DisclosureContent

This list is most likely not complete, as we're not using every single Paste component in the project. 

**To Reproduce**

1. Go to https://codesandbox.io/s/paste-starter-kit-forked-oqlm87?file=/src/index.tsx
2. See the TS error on `DisclosureContent` component
3. Downgrade Paste to 12
4. See that the TS error disappears.

**Expected behavior**
Paste 13 shouldn't require `css` property to be passed on random components.

**Screenshots**
![image](https://user-images.githubusercontent.com/2070479/169988595-30406b6b-94b3-41cc-b089-6aa7e09f28d4.png)

**Comment by nkrantz** [comment]
Hi @george-cz - knowing a little bit more about your environment will help us to determine what's going on here. Could you share your package.json?

**Comment by george-cz** [comment]
Hello, everything relevant should be obvious from the codesandbox I shared, the issue can be reproduced there.

If it isnt, please get in touch over Twilio slack and I can share the link to the internal repository :)

**Comment by shleewhite** [comment]
Hi @george-cz, thank you for your patience! We have just released a patch version of Paste that should resolve these issues. Please try upgrading @twilio-paste/core to 13.0.1 and let us know if you are still having the issue.

**Comment by TheSisb** [comment]
Hey all, 

I'll be closing this thread for now, but feel free to drop a comment if you continue to encounter this issue.
