### ISSUE TITLE
Spotted a documentation error on /components/flex with basis prop

### ISSUE THREAD

**Issue by thomaschaaf** [twilio-labs/paste#2432]
**Describe the bug**

The following usage 
```
    <Flex grow shrink basis>
```

results in invalid css. Because that results in `flex-basis: true;` as css.

**To Reproduce**

1. Go to https://paste.twilio.design/components/flex#flex-properties
2. Inspect "Left area"
3. See invalid css (also a warning from chrome)

**Expected behavior**

It should probably be

```
    <Flex grow shrink basis={1}>
```

per the API documentation at the end of the page `basis` may also not be boolean.

**Comment by nkrantz** [comment]
Hey @thomaschaaf - I just opened a PR (#2433) for this. Thanks for letting us know!

**Comment by thomaschaaf** [comment]
@nkrantz thanks by the way I went through the feedback and then report issue button. If I would have seen I could create a PR for the documentation I would have done that. Maybe an edit page link would be beneficial. See https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/translate at the bottom.

**Comment by nkrantz** [comment]
@thomaschaaf thank you for this feedback! I've shared it with the DSYS team. Feel free to open a PR going forward if you spot any more bugs, or open another Issue to alert the team.
