### ISSUE TITLE
External Link Icon

### ISSUE THREAD

**Issue by kateschwarz** [twilio-labs/paste#244]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

## Is this related to an existing Paste Component? Please link it here:
No

## Describe the functionality you're looking for
I am looking to add an icon similar to the current Console icon `.icon-twilio-external-link`
This icon will be used in the redesign of the Account/Project Switcher page in the Console.
![image](https://user-images.githubusercontent.com/54084724/71748679-8ac9a480-2e30-11ea-9e82-9323fe496420.png)

**Comment by TheSisb** [comment]
Hello @kateschwarz,

There's two ways this icon can be added:

1. We can add this task to our backlog to be prioritized within the next sprint or two.  This means you'll be waiting for 2-4 weeks before it's published.
2. Alternatively, we've documented [our self-service design approach](https://paste.twilio.design/icon-system/how-to-add-an-icon) that you can provide to your designers.  Once that is completed, you can open a PR against this repo and add your icon by [following this simple process](https://github.com/twilio-labs/paste/tree/master/packages/paste-icons#how-can-i-contribute-icons).

An example of a PR done recently by a console team can be seen here: 
https://github.com/twilio-labs/paste/pull/235

If no action is taken, we will proceed with the first approach.

If you have any additional questions or concerns, you can reply in this thread or reach out on Slack.
