### ISSUE TITLE
Line height doesn't scale with fontSize for Text

### ISSUE THREAD

**Issue by dholliday3** [twilio-labs/paste#2444]
I'm using the Text component with `fontSize="fontSize100"` and the line height is set to 1.25rem natively by the Text component. Why is this? Shouldn't line height be set to normal and then explicitly set by the lineHeight prop if needed? 

**Here's what it looks like out of the box:** 
![Screen Shot 2022-06-01 at 7 12 41 PM](https://user-images.githubusercontent.com/15958912/171534677-687eaef3-e595-4186-8272-22c01741c90b.png)

**Here's what it looks like if I change line-height to normal in the browser**
![Screen Shot 2022-06-01 at 7 12 47 PM](https://user-images.githubusercontent.com/15958912/171534792-dcec89eb-3c89-4895-b449-16c61df9a651.png)

**My code**
![image](https://user-images.githubusercontent.com/15958912/171535208-65f843e1-25e1-41aa-b035-3edb3deec5a2.png)

**Comment by TheSisb** [comment]
Hi @dholliday3,

After chatting with the team, we decided not to cause a breaking change with Text by automatically adding line-height. Our rationale is that the `Text` component enabled completely custom behaviors and that we should provide more semantically named, typographic components. This would allow the system to remain design future-proof with the least friction.  Thanks for the suggestion, it sparked an interesting discussion!

**Comment by dholliday3** [comment]
> 

Makes sense to me! 
FWIW, the Heading component is bold which is why we sometimes use large Text.

**Comment by serifluous** [comment]
> FWIW, the Heading component is bold which is why we sometimes use large Text. 

Nice, thanks for sharing! We've been mulling over typography styles for Display Text so this is super helpful input for what y'all are looking for.
