### ISSUE TITLE
Combobox docs has a broken example

### ISSUE THREAD

**Issue by Kosai106** [twilio-labs/paste#2450]
**Describe the bug**
An example in your Combobox documentation is not working as expected.

**To Reproduce**

1. Go to [Combobox with option groups](https://paste.twilio.design/components/combobox/#combobox-with-option-groups)
2. Select any item from the list
4. See error `ReferenceError: _ is not defined`

**Expected behavior**
A working example.

**Screenshots**
[Video example](https://share.getcloudapp.com/ApuXyXkb)

![Screenshot 2022-06-06 at 15 43 20](https://user-images.githubusercontent.com/6379824/172172690-78ed88bf-2ff8-47e7-9380-d82e9797c371.png)

**Desktop (please complete the following information):**

- OS: MacOS Monterey
- Browser: Google Chrome 102
- Version: -

**Additional context**
I tried locating the source of the docs in order to submit a PR myself but I couldn't locate it.

**Comment by SiTaggart** [comment]
Thanks @Kosai106, I just merged a fix for this and it should be going live any minute now!

Thanks for pointing it out!
