### ISSUE TITLE
New Icon - Twilio.org Impact Access Program

### ISSUE THREAD

**Issue by jsheppard-twilio** [twilio-labs/paste#247]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**
Add a new Icon - initially a single use case - for the main console navigation.
## Describe the functionality you're looking for
Add this new icon to the icon "icon-twilio-org-impact-access"

https://issues.corp.twilio.com/browse/MARK-5235

**Comment by TheSisb** [comment]
Hello @jsheppard-twilio,

There's two ways this icon can be added:

1. We can add this task to our backlog to be prioritized within the next sprint or two.  This means you'll be waiting for 2-4 weeks before it's published.
2. Alternatively, we've documented [our self-service design approach](https://paste.twilio.design/icon-system/how-to-add-an-icon) that you can provide to your designers.  Once that is completed, you can open a PR against this repo and add your icon by [following this simple process](https://github.com/twilio-labs/paste/tree/master/packages/paste-icons#how-can-i-contribute-icons).

An example of a PR done recently by a console team can be seen here: 
https://github.com/twilio-labs/paste/pull/235

If no action is taken, we will proceed with the first approach.

If you have any additional questions or concerns, you can reply in this thread or reach out on Slack.

**Comment by TheSisb** [comment]
Resolved in https://github.com/twilio-labs/paste/pull/270
Thanks!
