### ISSUE TITLE
Combobox `label` has no `html_for` attribute

### ISSUE THREAD

**Issue by HartiganHM** [twilio-labs/paste#2485]
Thanks for helping make Paste better! For general questions or feature requests, please post [a discussion](https://github.com/twilio-labs/paste/discussions/new).

**Describe the bug**
When using the `Combobox` component with an `id` property, this `id` prop does not correspond to an `html_for` attribute on the `label` when using `labelText`. This is breaking any of our tests that rely on the `findByLabelText` utility from RTL.

**To Reproduce**

1. Create a `Combobox` component with all necessary props and an `id` and `labelText`
2. Use Cypress with RTL and try to find the input using `cy.findByLabelText`
3. See the Cypress is unable to find the corresponding input by the `labelText` ([Example](https://dashboard.cypress.io/projects/mtkm64/runs/1633/test-results/765e5047-7e33-4aae-bf93-c6dcd7248091/screenshots))
4. Additionally, if you check the DOM via dev tools, you can see there is no `html_for` prop on the `label`

**Expected behavior**
The `Combobox` should pass the `id` prop to the `html_for` attribute of the corresponding `label` for proper accessibility.

**Screenshots**
> DOM of `label` with no `html_for`
> <img width="509" alt="image" src="https://user-images.githubusercontent.com/24458700/175017041-9a23a0e6-8450-49ea-b057-fecf44986033.png">

> Failing Cypress test
> <img width="1298" alt="image" src="https://user-images.githubusercontent.com/24458700/175016903-3c9e82c2-b69c-482e-9408-e4fd4dfe023c.png">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Electron/Chrome
- Version 94/102

**Additional context**
We recently swapped an `Input` component for `Combobox` and, prior to this swap, all of our tests were running as expected. Upon switching to the `Combobox` they're all failing. You can see an example suite of failing tests [here](https://dashboard.cypress.io/projects/mtkm64/runs/1633/test-results).

**Comment by TheSisb** [comment]
Hey @HartiganHM,

Comboboxes are a little different than traditional inputs in that they have specific requirements for associating the label, input, and menu correctly for accessibility. For this reason we let Downshift handle the `id` management for us, they do a great job at it. 

Coming from an `input` component which leaves it up to you, I can see how your old `id` prop isn't working as expected anymore.  In this case, I'd recommend swapping to a `data-testid` for your tests.  Here's a codesandbox that I used to work through the problem: https://codesandbox.io/s/adding-ids-to-combobox-for-testing-gg3qbo

![image](https://user-images.githubusercontent.com/1592327/175343492-074f45e1-e098-470a-9d5c-f4f0fe85519b.png)

You can see my `data-testid` being passed correctly to the input, and that downshift is still managing the `id` for me correctly.

Hope this helps!

**Comment by HartiganHM** [comment]
Hey, @TheSisb! Thanks for the follow-up and help. I get allowing Downshift handle `id` management if they're doing a great job. However, we've generally tried to stick to RTL's methodology of user facing accessors (e.g. label, text, alt, etc.). Is there a solution we can use in line with that or is `data-testid` the only solution?

Thanks in advance!

**Comment by TheSisb** [comment]
Hey @HartiganHM,

If strictly following React Testing Library, you can try either:

- `getByRole` to be [`combobox`](https://github.com/twilio-labs/paste/blob/main/packages/paste-core/components/combobox/__tests__/index.spec.tsx#L196) or [`textbox`](https://github.com/twilio-labs/paste/blob/main/packages/paste-core/components/combobox/__tests__/index.spec.tsx#L204) like our own tests.
- `getByLabelText` for whatever you choose to pass into the `labelText` prop for the Combobox

Both of those should work for you. Are you encountering any specific obstacles? The `id` prop shouldn't be recommended in React Testing Library I think.

**Comment by HartiganHM** [comment]
Hey, @TheSisb!

So, the `getByRole` might work, we'll give that a shot. As for `getByLabelText` that likely won't. My understanding is that `*ByLabelText` works by finding the `label` in question and uses the `html_for` attribute to find the corresponding input by its `id` (which is the problem I mention in the original bug issue).

We're not using the `id` to find the input, but my understanding is that it's required under the hood for any `*ByLabelText` accessors to work in RTL.

**Comment by TheSisb** [comment]
Hi @HartiganHM,

Oooh I misunderstood your first post, sorry! There actually is an htmlFor on the label, it gets converted from `htmlFor` (React) to `for` (Html):

> Note: To programmatically set the for attribute, use [htmlFor](https://developer.mozilla.org/en-US/docs/Web/API/HTMLLabelElement/htmlFor).

Source https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#attr-for

Your DOM screenshot shows a `for` attribute on the label:
![image](https://user-images.githubusercontent.com/1592327/176199712-98bb830a-d4e4-4575-bac0-6ca038155120.png)

Looking at your Cypress error again, I'm seeing:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/1592327/176200181-44322f41-fcda-46a2-b93b-ef1d5aac803a.png">

Could there have been another issue? `ByLabelText` _should_ work just fine I think.

**Comment by HartiganHM** [comment]
@SiTaggart I was actually coming back to write that we were overriding the `id` prop! So, yes, that's on us. We do this for some scrolling behavior on our end, though we'll probably find an alternative solution with this in mind.

Thanks for the insight to you and @TheSisb!
