### ISSUE TITLE
Better Documentation Around Fonts

### ISSUE THREAD

**Issue by GiantRobots** [twilio-labs/paste#257]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

## Is this related to an existing Paste Component? Please link it here:

Currently we use REM's for font sizes which requires a specific font to be set on the HTML tag. I believe it's 16px. This isn't well documented in installation or anywhere else making design-tokens difficult to use.

## Describe the functionality you're looking for

More documentation surrounding setting up the document font size to allow REM to work correctly.

**Comment by TheSisb** [comment]
How are you using the tokens? The `ThemeProvider` should set the font-size on the html tag appropriately, see https://github.com/twilio-labs/paste/blob/master/packages/paste-theme/src/themeProvider.tsx#L14.

**Comment by GiantRobots** [comment]
We're not using the theme provider because we're using design-tokens to do a best effort mapping from paste design-tokens to sendgrid css. Without some of that information you can't use design-tokens through sass without guessing/digging

**Comment by SiTaggart** [comment]
It's a fair callout. I think we probably need a page on Typography to give these kind of details, but we haven't gotten to it yet.

The reason we haven't prioritised it is that the assumption is consumers of Paste will on the whole either live inside Console, Flex or SendGrid, and from our findings those already set the html font size to 16px already. This means it _should_ then work out the box.

But yes, we do need to create a Typography page to outline the pre-requesites for getting started with the various font families, or add it to the engineering getting started page.

**Comment by GiantRobots** [comment]
Thinking something like this might help?
<img width="1319" alt="Screen Shot 2020-01-14 at 10 20 51 AM" src="https://user-images.githubusercontent.com/1903839/72370798-d9403400-36b7-11ea-804a-c87b721db6a5.png">

**Comment by GiantRobots** [comment]
https://github.com/twilio-labs/paste/pull/259

**Comment by richbachman** [comment]
@GiantRobots do you consider this issue resolved with your documentation PR?

**Comment by GiantRobots** [comment]
Yup!
