### ISSUE TITLE
ComboBox dropdown is cut off when inside a ModalBody component

### ISSUE THREAD

**Issue by robnit** [twilio-labs/paste#2630]
**Describe the bug**
ComboBox dropdown is cut off when inside a ModalBody component. See codesandbox here: https://codesandbox.io/s/silly-stitch-t0j1j6?file=/src/App.tsx

**To Reproduce**
1. Create a ComboBox component with lots of items inside a ModalBody
2. Open the ComboBox dropdown

**Expected behavior**
ComboBox dropdown should overlap everything just like a standard Select component dropdown

**Screenshots**
![Screen Shot 2022-08-23 at 10 17 12 AM](https://user-images.githubusercontent.com/28577914/186223356-10a2bb24-933c-4ce5-9844-7db93c5255e2.png)
![Screen Shot 2022-08-23 at 10 17 23 AM](https://user-images.githubusercontent.com/28577914/186223362-33190a3c-c345-49a7-90e0-b354de6f5c1b.png)

**Desktop (please complete the following information):**

- Browser : Chrome Version 104.0.5112.79 (Official Build) (x86_64)
- Version 10.2.0

**Comment by shleewhite** [comment]
Closing this in favor of this discussion post: https://github.com/twilio-labs/paste/discussions/2622.
