### ISSUE TITLE
Publish Theo formatters on NPM for others to use?

### ISSUE THREAD

**Issue by voxpelli** [twilio-labs/paste#268]
While looking for what other has done with Theo I found that you have been doing some pretty cool things with it, like generating a Sketch palette: https://github.com/twilio-labs/paste/blob/master/packages/paste-design-tokens/formatters/sketchpalette.ts

I think it would be great if you would publish such unique formatters independently on npm so that others, like me, could use them and contribute to them independently of Paste itself.

We're currently creating our own design guide / patter library at work and would be great to build upon work that has already been done and to contribute back whatever else we might add to it 👍

**Comment by SiTaggart** [comment]
Hi @voxpelli, that's certainly an interesting idea. The easiest thing would be just to export them from the design token package but I feel like that wouldn't be entirely helpful for the community on a whole.

I could see the need or use for a crowdsourced repository of theo formatters that others could contribute to, too. Save all these companies reinventings (or copy and pasting as I did 😉 ).

Let me think about. Alternatively, you could create that repo for the wider community and we contribute our formatters to it.

**Comment by SiTaggart** [comment]
Closing this for now as I would like to see this as an external resource or community repo.
