### ISSUE TITLE
Update SendGrid palette-gray-70 value

### ISSUE THREAD

**Issue by two24studios** [twilio-labs/paste#269]
**Describe the bug**
The value of gray was updated in the Sketch components to get a gray color closer to 3:1 on a white background. The value needs to be: `#8894AA`

**To Reproduce**
Not steps needed to reproduce, the value just needs to be updated for the alias.

**Expected behavior**
Value for alias `palette-gray-70` equals `#8894AA`

**Additional context**
See: https://share.goabstract.com/c890868b-5aae-4acb-bc06-01105af3624f?

**Comment by aayushpi** [comment]
Moved to backlog
