### ISSUE TITLE
Convert to Outlines shortcut needs an update

### ISSUE THREAD

**Issue by sangster009** [twilio-labs/paste#273]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the issue**
Convert to Outlines on https://github.com/twilio-labs/paste/issues/new/choose (edited)  says "SHIFT + COMMAND + O it should be "OPTION + COMMAND + O"

**Comment by serifluous** [comment]
Thanks, Sang!
