### ISSUE TITLE
Lorem Ipsum is distracting and not valuable

### ISSUE THREAD

**Issue by JT1989** [twilio-labs/paste#279]
**Problem**

- It's distracting to see Lorem Ipsum in the examples.

<img width="780" alt="Screen Shot 2020-01-24 at 2 42 51 PM" src="https://user-images.githubusercontent.com/8630856/73109749-ea0f5780-3eb8-11ea-83f9-430922231bd5.png">

https://paste.twilio.design/components/list

-  It's strange to see a mix of real-world use of the component with irrelevant copy with filler copy.

<img width="776" alt="Screen Shot 2020-01-24 at 2 54 16 PM" src="https://user-images.githubusercontent.com/8630856/73109909-715ccb00-3eb9-11ea-83fc-5cc97171cfa1.png">

https://paste.twilio.design/components/card

**Suggested Solution**
Let's see a **consistent** use of real data and real copy. 

Do some research and put something in there. If you need ideas, please reach out to the team. 

For example, seeing real copy below gives us all a chance to see and use consistent voice and tone and it shows thoughtfulness towards a customer-obsessed experience.

<img width="777" alt="Screen Shot 2020-01-24 at 2 43 01 PM" src="https://user-images.githubusercontent.com/8630856/73109722-d532c400-3eb8-11ea-8a56-a92c80afc5a6.png">

**Comment by serifluous** [comment]
This is a great point. We’ll work with Caroline on component copy guidelines and put some real content in our component examples

**Comment by JT1989** [comment]
Awesome! @serifluous, for your Form Fields project, you can use this example for suffixes:
<img width="531" alt="Screen Shot 2020-02-04 at 9 45 21 AM" src="https://user-images.githubusercontent.com/8630856/73773843-c1e4eb80-4737-11ea-9c2a-df02fcc7ea54.png">

For prefixes, you can use status callback webhooks as a use case/example within the documentation

**Comment by aayushpi** [comment]
Moved to Backlog. Thank you @JT1989
