### ISSUE TITLE
Unexpected mandatory props for paste icons

### ISSUE THREAD

**Issue by pranshuchittora** [twilio-labs/paste#2832]
### Description

Hey I am using the latest version of icons. And for the past few major versions I am getting error to add missing props.

https://user-images.githubusercontent.com/32242596/201998791-37f405a3-b3fb-479a-9b7f-84285e982439.mov

But on codesandbox I am not getting this issue with the latest paste-core, but able to replicate the same with paste core version 10.20.0

```
"@twilio-paste/core": "10.20.0",
"@twilio-paste/icons": "9.4.0",
```

### Link to Reproduction

https://codesandbox.io/s/angry-spence-73k0mw?file=/src/index.tsx

### Paste Core Version

10.20.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by SiTaggart** [comment]
Hi There

We usually see people encounter this issue when they are running on older version of Core. I can see you are using `"10.20.0"`.

Can you update to Core v17? I suspect your issues will go away at that point.

Thank
