### ISSUE TITLE
Select component nests Style element, which is not to HTML5 spec

### ISSUE THREAD

**Issue by dprothero** [twilio-labs/paste#2842]
### Description

When you use the `Select` component, it renders a `<style>` tag nested under the `<select>` tag, like so:

```html
      <select
        id="platform-5231"
        name="platform"
      >
        <style data-emotion-css="1raivgc">
          .css-1raivgc {
            box-sizing: border-box;
            background-color: inherit;
            color: inherit;
            font-family: inherit;
            line-height: 1.75rem;
            padding-top: 0.5rem;
            padding-bottom: 0.5rem;
            padding-left: 0.25rem;
          }
        </style>
        <option
          selected=""
          data-paste-element="OPTION"
          value="all"
          class="css-1raivgc"
        >
          All
        </option>
        <option
          data-paste-element="OPTION"
          value="universal"
          class="css-1raivgc"
        >
          Universal
        </option>
        <option
          data-paste-element="OPTION"
          value="unknown"
          class="css-1raivgc"
        >
          Unknown
        </option>
      </select>
```

However, this is not _technically_ valid HTML, even if it does seem to work in the browser.

[Here's the reference to the spec](https://www.w3.org/TR/2011/WD-html5-20110405/the-button-element.html#the-select-element). You can see "Content model" can only be Zero or more `<option>` or `<optgroup>` tags.

I'm not strictly being pedantic here. We ran into an issue with the search engine we are using, [Pagefind.app](https://pagefind.app), where it blows up because of this. I'm also working with them to see if there's a workaround, but I thought I would report it here as well.

### Link to Reproduction

https://paste.twilio.design/components/select#base-select

### Steps to reproduce

1. Go to https://paste.twilio.design/components/select#base-select
2. Right-click and choose "View source"
3. Search for `<select data-paste-element`
4. You will see a `<style>` tag nested under it

### Paste Core Version

11.5.0 (but happens on Docs site, too)

### Browser

any

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by dprothero** [comment]
Update: Pagefind fixed their tool to no enforce strict HTML checking, so we're unblocked. This is mostly an FYI.

**Comment by SiTaggart** [comment]
Hi @dprothero 

Yeah, it is kind of a “known issue” with Emotion and Server Side Rendering. When the JavaScript isn’t enabled the default behavior is injected style blocks in or around the component being rendered.

They allude to it being problematic with first child, last child selectors a little and there are a couple of rendering options available to try https://emotion.sh/docs/ssr

We obviously just do what ever the default is.

I’ll leave this here for now, and think about if we need to provide guidance around this further.

**Comment by TheSisb** [comment]
As of Paste core `v19.1.0`, you can provide options to the underlying Emotion CacheProvider as [seen in this discussion](https://github.com/twilio-labs/paste/discussions/3196#discussioncomment-5800454). While the demo showcases injected the styles and components into the shadow-dom, you may also use it to control where the styles get injected in your own application.  This should provided a solution to your reported issue.
