### ISSUE TITLE
Error when following Card example in Docs. 

### ISSUE THREAD

**Issue by aking-twilio** [twilio-labs/paste#2848]
### Description

When following Card example, the following Error is generated in the Console. 

> Uncaught Error: [Paste: Button] Using Button component as an Anchor. Use the Paste Anchor component instead.

However, in the documentation for [Card with Title, Body and Button](https://paste.twilio.design/components/card#card-with-title-body-and-button) an example is given which uses:

`      <Button variant="primary" as="a" href="https://alp.org/">Support The Audre Lorde Project</Button>
`

Is it a case of Docs need updating? Or did I do something else wrong?

### Link to Reproduction

https://paste.twilio.design/components/card#card-with-title-body-and-button

### Steps to reproduce

Use <Button as="a" ...> in code, as per docs example for Card.

### Paste Core Version

15.1.0

### Browser

Chrome 

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by TheSisb** [comment]
Hi @aking-twilio,

`<Button as="a" href="#"` only works if you also pass the `variant="primary or secondary"`

The error you are seeing occurs if you use `as="a" href="http://..." variant="link or inverse_link"`, in which case it both looks and behaves as an Anchor, so an Anchor should be used.

The logic for these errors can be reviewed in the [Button's index.tsx](https://github.com/twilio-labs/paste/blob/main/packages/paste-core/components/button/src/index.tsx#L89) file

Hope this helps!

**Comment by aking-twilio** [comment]
Makes sense, thank you. Feel free to close this issue.
