### ISSUE TITLE
Badge component allow passing properties on development time

### ISSUE THREAD

**Issue by jmauriciosalasmoreno** [twilio-labs/paste#3070]
### Description

When I write props for the Badge component and the props is not an allowed combination, I expect the linter to show an error.
**What is happening right now is:** It shows the error on runtime, resulting on a blank error screen

### Link to Reproduction

https://codesandbox.io/s/bold-firefly-b63b99

### Steps to reproduce

1. Go to '[the code sandbox](https://codesandbox.io/s/bold-firefly-b63b99)'
2. See error

### Paste Core Version

16.1.0

### Browser

Google Chrome Version 110.0.5481.177 (Official Build) (arm64)

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

In our codebase, the props we pass to the Badge component, are computed giving specific conditions
One of the combinations was close to generate an incident. In order to improve this, in our code base we added stronger TypeScript types to avoid such situation. We think other developers can benefit from that approach, this is an example of how this can be solved using TypeScript:

```typescript
type Impossible<K extends keyof any> = {
  [P in K]: never;
};

type NoExtraProperties<T, U extends T = T> = U & Impossible<Exclude<keyof U, keyof T>>;

type ActionableBadgeProps =
  | NoExtraProperties<{
      as: 'a';
      href: string;
    }>
  | NoExtraProperties<{
      as: 'button';
      onClick: React.HTMLAttributes<HTMLButtonElement>['onClick'];
    }>
  | NoExtraProperties<{
      as: 'span';
    }>;

```

**Comment by jmauriciosalasmoreno** [comment]
Another simple solution in [the types](https://github.com/twilio-labs/paste/blob/3c89fd83d09c0f49e362c4d33ade4d3688d7381a/packages/paste-core/components/badge/src/types.ts#L22) could be something like: 

```typescript
... & {
    variant: BadgeVariants;
    children: NonNullable<React.ReactNode>;
} & ({
    as: 'a';
    href: string;
    onClick?: never;
} | {
    as: 'button';
    onClick: ...;
    href?: never;
} | ...)
    
    
```

**Comment by SiTaggart** [comment]
Hi @jmauriciosalasmoreno 

Good call out and suggestions on improved typings. I've attempted to take those and apply them to Badge to help you catch invalid props at compile time.

I've also just remove the prop validation as it feels redundant at this point.

Follow along in the PR https://github.com/twilio-labs/paste/pull/3078

**Comment by SiTaggart** [comment]
These updated types are merged. Expect them to be in the next release of Paste which should come in the next week.
