### ISSUE TITLE
Combobox List out of View in Modal After Scroll

### ISSUE THREAD

**Issue by alfrimpong** [twilio-labs/paste#3097]
### Description

When a page is long enough and a user scrolls downs before activating a modal that contains a combobox, the combobox list is stuck near the top of the page. 

### Link to Reproduction

 https://codesandbox.io/s/codepen-with-react-forked-vkvo0m?file=/src/components/App.js

### Steps to reproduce

1. Scroll down a bit, then click "OPEN MODAL"
2. _Notice the list of languages is out of place._
3. Close the modal
4. Scroll to the top of the page then click "OPEN MODAL"
5. _Notice the list of languages is where it should be._

### Paste Core Version

18.1.0

### Operating System

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by SiTaggart** [comment]
Hi @alfrimpong 

Thanks for submitting this, I've added this to our backlog to address. We'll circle back here once it's addressed

**Comment by SiTaggart** [comment]
This should be fixed in 19.0.1. Please let us know if it isn't.
