### ISSUE TITLE
Links on console are using default text color 

### ISSUE THREAD

**Issue by samarthpuri** [twilio-labs/paste#3099]
### Description

I've been noticing for a while now that the links in Console are using the default text color instead of the usual blue. Attached some screenshots as examples

<img width="267" alt="Screen Shot 2023-03-15 at 2 54 42 PM" src="https://user-images.githubusercontent.com/23617133/225440482-ee606800-2633-4b26-9f5c-4b8e3065eec5.png">
<img width="348" alt="Screen Shot 2023-03-15 at 2 54 13 PM" src="https://user-images.githubusercontent.com/23617133/225440487-d2a42c8b-a6e9-4ced-927c-49b9d1f9111a.png">
<img width="177" alt="Screen Shot 2023-03-15 at 2 53 49 PM" src="https://user-images.githubusercontent.com/23617133/225440489-e51d831f-3c44-4f3c-96c8-806359ea71d9.png">
<img width="185" alt="Screen Shot 2023-03-15 at 2 53 38 PM" src="https://user-images.githubusercontent.com/23617133/225440491-41eabcb9-b86d-4304-8574-0f2399ea13b4.png">

### Link to Reproduction

https://console.twilio.com/us1/develop/verify/services

### Steps to reproduce

1. Go to 'https://console.twilio.com/us1/develop/verify/services'
2. Click on 'Learn more the paragraph under the header'

### Paste Core Version

18.1.0

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by SiTaggart** [comment]
Hi @samarthpuri 

This is a problem with the Verify app. Someone is injecting global CSS into the page which is breaking all links within the Verify app. 

<img width="574" alt="image" src="https://user-images.githubusercontent.com/368249/225450848-b9f23f9d-14e8-4b9b-9c6d-c67ca67931ee.png">

What every [tooltip this is creating](https://github.com/twilio-internal/console/blob/345c6916fbc832b0592dbcdab0457b92f7486bd6/apps/console/src/app/applications/Verify/pages/fraudInsights/main/components/TopCountriesTab/TopCountriesCharts/tooltips/index.tsx#L2) needs to use Paste tooltips.

Lastly, no Console app should be importing global CSS as you'll break styling on existing components on the page.
