### ISSUE TITLE
Side Modal doesn't extend to the full height of the page

### ISSUE THREAD

**Issue by bthomasstill** [twilio-labs/paste#3101]
### Description

When I add the side modal component to my page and open the side modal, it doesn't extend the full height of the page (as it does in the Paste docs). The component behaves the same whether it is placed within enclosing html/styling or placed on the page un-nested. I've tested it and it is fixed by changing `position: absolute` to `position: fixed` on the `SideModalContainer` component.

![Screenshot 2023-03-16 at 16 44 27](https://user-images.githubusercontent.com/114398889/225694355-05301308-42a2-4df8-b115-b0bf63b97f93.png)

### Link to Reproduction

https://codesandbox.io/s/bold-thompson-g4l7mg?file=/src/index.tsx

### Steps to reproduce

1. Go to gode sandbox
2. Click on side modal button
3. Scroll down to the bottom of the page
4. See that side modal does not extend the length of the page.

### Paste Core Version

18.0.0

### Browser

Version 111.0.5563.64

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by SiTaggart** [comment]
Hi @bthomasstill 

Thanks for the bug report, does indeed look like a problem, especially if you have long pages and scroll. I'll look at putting in a fix for this over the next couple of days

**Comment by bthomasstill** [comment]
Great, thanks!

**Comment by SiTaggart** [comment]
Released in Paste Core v19

**Comment by bthomasstill** [comment]
Hi, following up on this. We've just recently upgraded Paste to v19 but still seeing this issue. I think the problem is that there is internal logic that overrides the default `'position: fixed` styling to `position: absolute` when the side modal opens.

**Comment by SiTaggart** [comment]
Hi @bthomasstill 

Are you sure the upgrade was successful? Even on the Codesandbox you provided which uses the latest version of Paste, I'm not seeing the style change to absolute. Could it be that the upgrade didn't work correctly?

<img width="398" alt="image" src="https://user-images.githubusercontent.com/368249/236078187-5c25786e-a688-4fd6-b0cb-78844a6eb3ea.png">

**Comment by bthomasstill** [comment]
Yeah, good point, code sandbox is working as expected. I'll investigate on our side but most likely not further action needed on Paste side. Thanks!
