### ISSUE TITLE
Feedback - Translating designs to Paste components

### ISSUE THREAD

**Issue by Angelangg** [twilio-labs/paste#312]
This is just feedback for the team. As a designer, I wasn't clear on how to translate my designs into Paste components for my engineer to start building. One example of this is I have text on the page and when I looked at Paste, I saw initially didn't see anything for text except under utilities. Now text is moved under primitives which make sense. I was confused about what utilities were so I tried to look for more relevant information about text. That led me to the token list where I saw the text tokens so I thought those were the only things I needed for my engineer. I think we need more explicit documentation of how to translate designs from sketch/Abstract to Paste components that engineers can use to start building.

**Comment by serifluous** [comment]
Hey @Angelangg, for context, can you send us the screen designs you’re trying to build? You can drop them in the Slack help channel.

**Comment by TheSisb** [comment]
Closing because stale.
