### ISSUE TITLE
Modal `className` isn't forwarded

### ISSUE THREAD

**Issue by brandongregoryscott** [twilio-labs/paste#3184]
### Description

It looks like the `Modal` component does not forward/append the `className` prop it is given like the `Box` component does. I did a quick search for similar issues and came across https://github.com/twilio-labs/paste/discussions/761. If this intentionally being locked down to prevent incosistency/hacky behaviors, then the `className` prop should be omitted from the TS definition to prevent confusion. 

In my case, I am trying to add a class name to [unmask the modal in Full Story](https://help.fullstory.com/hc/en-us/articles/360044349073-FullStory-Private-by-Default).

### Link to Reproduction

https://codesandbox.io/s/modal-classname-isnt-forwarded-djivkp?file=/src/index.tsx

### Steps to reproduce

1. Inspect the DOM
1. Notice the className `my-modal` is not present in any of the modal DOM elements, while the className `my-box` is.

### Paste Core Version

19.0.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by TheSisb** [comment]
Hi @brandongregoryscott,

Long story short, Paste doesn't allow passing `className` or `style` to our components for the reasons outlined in the other discussion that you've linked.  Good catch in that our types don't really make that clear! I'm making a ticket in our backlog to remedy that.
