### ISSUE TITLE
Twilio Paste Intellisense installation link is incorrect

### ISSUE THREAD

**Issue by brandongregoryscott** [twilio-labs/paste#3189]
### Description

The installation link in the README for the extension points to @gkassym's publisher account, not the `TwilioPaste` version

![image](https://user-images.githubusercontent.com/11774799/234084709-5cf9474d-d756-4c8b-a059-dfd54f3a4155.png)

```diff
-https://marketplace.visualstudio.com/items?itemName=Gapur.twilio-paste-intellisense 
+https://marketplace.visualstudio.com/items?itemName=TwilioPaste.vs-code-intellisense
```

### Link to Reproduction

https://marketplace.visualstudio.com/items?itemName=TwilioPaste.vs-code-intellisense

### Steps to reproduce

1. Hover over link for installation
1. Notice the publisher is incorrect 

### Paste Core Version

--

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by TheSisb** [comment]
Thanks! Will make a PR shortly to fix this. 

Aside, you've contributed more than once to this plugin. Would you like to be added to the contributors list in the [package.json](https://github.com/twilio-labs/paste/blob/main/apps/vs-code-intellisense/package.json) (and eventually on our website)?

**Comment by brandongregoryscott** [comment]
>Would you like to be added to the contributors list in the [package.json](https://github.com/twilio-labs/paste/blob/main/apps/vs-code-intellisense/package.json?rgh-link-date=2023-04-24T19%3A10%3A06Z) (and eventually on our website)?

Sure thing! 😄  Appreciate it.

**Comment by brandongregoryscott** [comment]
@TheSisb Was a new version of the extension released with https://github.com/twilio-labs/paste/pull/3163?

**Comment by TheSisb** [comment]
@brandongregoryscott Not yet, we'll get to it soon with this fix.

**Comment by TheSisb** [comment]
Fixed in the latest plugin release!
