### ISSUE TITLE
[Documentation] react-spring config comments are out of date

### ISSUE THREAD

**Issue by brandongregoryscott** [twilio-labs/paste#3197]
### Description

Hey team - I'm sure you're probably tired of me opening up documentation related tickets by now, but it's honestly probably easier for you folks to update vs. me opening up a PR on my fork and having to close it out & open up a separate PR for the full CI suite/etc.

There's a few code comments for components that use `react-spring` that refer to https://www.react-spring.io/docs/hooks/api for info on the `config` object, but that link is broken. The new page is https://www.react-spring.dev/docs/advanced/config

Should be a quick find & replace if ya'll care to keep it there - right now it's not super useful since it's a broken link.

### Link to Reproduction

https://github.com/twilio-labs/paste/blob/45a7753e8b4788029e8863da9d1e74c1482df5b3/packages/paste-core/components/modal/src/Modal.tsx#L84

### Paste Core Version

--

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by TheSisb** [comment]
> Hey team - I'm sure you're probably tired of me opening up documentation related tickets by now, but it's honestly probably easier for you folks to update vs. me opening up a PR on my fork and having to close it out & open up a separate PR for the full CI suite/etc.

Not at all! We appreciate these very much!

We'll tackle all of these in one PR soon. Thank you!
