### ISSUE TITLE
Sidebar, Topbar pages results in 404

### ISSUE THREAD

**Issue by josephmarkus** [twilio-labs/paste#3237]
### Description

When visiting Sidebar or Topbar pages, 404 message displays

### Link to Reproduction

https://paste.twilio.design/components/sidebar

### Steps to reproduce

1. Go to https://paste.twilio.design/components/sidebar
2. Observe 'Sidebar' in left hand side navigation
3. Observe "Oops, this page doesn't exist" on the main page

Same applies to Topbar page

<img width="933" alt="Screenshot 2023-05-18 at 12 23 09" src="https://github.com/twilio-labs/paste/assets/9258365/7927b4ad-79fc-4680-9217-4dd2cb3cd331">

<img width="956" alt="Screenshot 2023-05-18 at 12 28 59" src="https://github.com/twilio-labs/paste/assets/9258365/1c4bc569-24a3-4fa6-a0a0-08cabc67e30b">

### Paste Core Version

19.1.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by loreina** [comment]
Hi @josephmarkus,

Thanks for reporting this - we're actively building out those components and expect to have the docs up for our next release. Appreciate your patience!

**Comment by ryanrouleau** [comment]
Hi @loreina , do you have an estimated release date for this side bar component?  Thanks

**Comment by SiTaggart** [comment]
Hi @ryanrouleau 

Soon, maybe two weeks 🤞🏼 

There's just a few more things to ship for Sidebar and Topbar to round it out as a collection. The docs are in PR waiting for a few more components to make it in https://github.com/twilio-labs/paste/pull/3217

**Comment by SiTaggart** [comment]
These are still in development, but we are at least handling the situation better now on the doc site itself. So closing this issue
