### ISSUE TITLE
Custom theme: Type 'string' is not assignable to type '"0.75rem"'

### ISSUE THREAD

**Issue by josephmarkus** [twilio-labs/paste#3239]
### Description

I followed instructions to create a custom theme here - https://paste.twilio.design/customization/creating-a-custom-theme#create-a-custom-theme-using-the-paste-theme-designer

I used theme generator from https://remix.twilio.design/ where I adjusted a background colour from white to red and exported the file.

After importing I got everything to work okay, but TypeScript shows an error about type incompatibility:

```
Type '{ shadows: { shadow: string; shadowBorder: string; shadowBorderBottomDecorative10Weaker: string; shadowBorderBottomDecorative20Weaker: string; shadowBorderBottomDecorative30Weaker: string; ... 54 more ...; shadowLow: string; }; ... 21 more ...; dataVisualization: { ...; }; }' is not assignable to type 'Partial<GenericThemeShape>'.
  The types of 'iconSizes.sizeIcon05' are incompatible between these types.
    Type 'string' is not assignable to type '"0.75rem"'.ts(2322)
CustomizationProvider.d.ts(46, 5): The expected type comes from property 'theme' which is declared here on type 'IntrinsicAttributes & CustomizationProviderProps & { children?: ReactNode; }'
```

### Link to Reproduction

https://codesandbox.io/s/paste-theme-bug-jo0q6g

### Steps to reproduce

1. Go to the Sandbox
2. Observe red error squiggle under `theme` prop with the following error:
```
Type '{ shadows: { shadow: string; shadowBorder: string; shadowBorderBottomDecorative10Weaker: string; shadowBorderBottomDecorative20Weaker: string; shadowBorderBottomDecorative30Weaker: string; ... 54 more ...; shadowLow: string; }; ... 21 more ...; dataVisualization: { ...; }; }' is not assignable to type 'Partial<GenericThemeShape>'.
  The types of 'iconSizes.sizeIcon05' are incompatible between these types.
    Type 'string' is not assignable to type '"0.75rem"'.ts(2322)
CustomizationProvider.d.ts(46, 5): The expected type comes from property 'theme' which is declared here on type 'IntrinsicAttributes & CustomizationProviderProps & { children?: ReactNode; }'
```

### Paste Core Version

19.1.0

### Browser

Google Chrome 113.0.5672.126

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by SiTaggart** [comment]
Hi @josephmarkus 

Good spot! Looks like if I remove the entire iconSizes key from the custom theme object, the type errors go away. So we must have a typing issue with iconSizes.

We'll create a ticket for this and update you when we've had a chance to address this.

Thanks for bringing it to our attention!
