### ISSUE TITLE
Recommended module imports lead to large bundle sizes

### ISSUE THREAD

**Issue by josephmarkus** [twilio-labs/paste#3247]
### Description

The documentation [suggests](https://paste.twilio.design/introduction/for-engineers/quickstart#paste-components) imports, such as:

`import {Box} from '@twilio-paste/core/box';`

but this leads to large bundle sizes.

The same import can be used as:

`import {Box} from '@twilio-paste/box';`

leading to much smaller bundle sizes

## Before

<img width="250" alt="Screenshot 2023-05-24 at 12 22 11" src="https://github.com/twilio-labs/paste/assets/9258365/0d9d37fb-949c-4e6a-bb23-2304972156ba">

## After

<img width="249" alt="Screenshot 2023-05-24 at 12 22 18" src="https://github.com/twilio-labs/paste/assets/9258365/42ef7c7c-86e2-43d4-ad71-36c85210abba">

### Link to Reproduction

#

### Steps to reproduce

1. Try the above imports using create-next-app
2. Compare output after `yarn build`

### Paste Core Version

19.1.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by TheSisb** [comment]
I'm closing this as stale for now. Please re-open if you're able to provide more information / a reproduction. Thanks!
