### ISSUE TITLE
CalloutHeading.as prop is marked as required in propTypes but not TypeScript definitions

### ISSUE THREAD

**Issue by brandongregoryscott** [twilio-labs/paste#3273]
### Description

This component will log a warning via `prop-types` if `as` is not provided, but it's marked as optional:

https://github.com/twilio-labs/paste/blob/da61a7b9d500e8787635aef9ae47bec50fb8931c/packages/paste-core/components/callout/src/CalloutHeading.tsx#L8

https://github.com/twilio-labs/paste/blob/da61a7b9d500e8787635aef9ae47bec50fb8931c/packages/paste-core/components/callout/src/CalloutHeading.tsx#L33

### Link to Reproduction

N/A - should be easy enough to reproduce

### Steps to reproduce

N/A

### Paste Core Version

19.0.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by SiTaggart** [comment]
Proptypes are annoying. Thanks for spotting it. I'll try and put a fix in as soon as I can
