### ISSUE TITLE
Sketch Symbol for Filter & Search is buggy

### ISSUE THREAD

**Issue by JT1989** [twilio-labs/paste#331]
**Describe the bug**
The symbol for filter & search toggle is buggy or incorrectly created

**To Reproduce**
1. Go to Abstract
2. Open the Tables & Filters library
3. Choose "Selected"
4. Choose "Unselected"

**Expected behavior**
-- When you choose "Selected," it uses the Filter icon
-- When you choose "Unselected," it uses the Filter icon 

When you choose "Unselected," the icon should use the Filter icon for consistency

**Current behavior**
-- When you choose "Selected," it uses the Filter icon
-- When you choose "Unselected," it uses the Search icon 

**Screenshots**
<img width="207" alt="Screen Shot 2020-02-25 at 12 09 17 PM" src="https://user-images.githubusercontent.com/8630856/75287683-a79aac80-57cf-11ea-969c-af4f63cb28ec.png">

<img width="542" alt="Screen Shot 2020-02-25 at 11 59 59 AM" src="https://user-images.githubusercontent.com/8630856/75287686-a8334300-57cf-11ea-887c-069f5de2d5c1.png">

**Comment by serifluous** [comment]
Thanks, JT! Added a ticket to our backlog.

**Comment by serifluous** [comment]
Merged in a fix in Sketch/Abstract. Confirmed through Slack that the issue's fixed 👍
