### ISSUE TITLE
Page does not exist

### ISSUE THREAD

**Issue by IAMMIA** [twilio-labs/paste#3310]
### Description

When I wanted to visit https://paste.twilio.design/patterns/navigation I received an error 404 page.

### Link to Reproduction

https://paste.twilio.design/patterns/navigation

### Steps to reproduce

1. Go to 'https://paste.twilio.design/patterns/navigation'
2. See error 404

### Paste Core Version

web

### Browser

Version 114.0.5735.198 (Offizieller Build) (x86_64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by TheSisb** [comment]
Hi @IAMMIA 

Sorry for the confusion here. The page is being built and will be coming soon. It shouldn't be showing up in the Sidebar yet, that was in error.

**Comment by TheSisb** [comment]
Page no longer shows in the Sidebar.
