### ISSUE TITLE
User Dialog modal has incorrect position in `@twilio-paste/core` 19.7.0

### ISSUE THREAD

**Issue by btjfsu** [twilio-labs/paste#3401]
### Description

When upgrading to `@twilio-paste/core` 19.7.0, it looks like the positioning of the `user-dialog` modal was affected as the modal now expands the `topbar` instead of over laying the `topbar`.

Version 19.6.0 works as expected in this CodeSandbox --> https://codesandbox.io/s/crazy-jennings-9gc4sh
Version 19.7.0 that shows the issue that was found in this CodeSandbox --> https://codesandbox.io/s/busy-maria-3lvwm9

Note that `useUserDialogState` also changes the positioning of the User Dialog Modal to open within its container as opposed to overlay. Without the `useUserDialogState`, the user dialog modal opens below the rendered components. 

### Link to Reproduction

https://codesandbox.io/s/busy-maria-3lvwm9

### Steps to reproduce

1. Starting from Version 19.6.0 https://codesandbox.io/s/crazy-jennings-9gc4sh, clone the code sandbox
2. Upgrade the `@twilio-paste/core` version to 19.7.0.
3. Click on the user dialog icon.
4. The modal expands the topbar instead of overlay upon the topbar.

### Paste Core Version

19.7.0

### Browser

Google Chrome 115

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by SiTaggart** [comment]
Super weird, I'll take a look. Thanks for the clean repro!

**Comment by SiTaggart** [comment]
Yup, OK, my bad. Quite literally, I broke it. Patch coming out today. Thanks for the speedy updating of versions 😉

**Comment by SiTaggart** [comment]
Just waiting for this to go out https://github.com/twilio-labs/paste/pull/3406 to create v20.0.1

**Comment by btjfsu** [comment]
> Just waiting for this to go out #3406 to create v20.0.1

Sounds good! Thanks @SiTaggart!

**Comment by SiTaggart** [comment]
> > Just waiting for this to go out #3406 to create v20.0.1
> 
> 
> 
> Sounds good! Thanks @SiTaggart!

It's out. It is a whirl
