### ISSUE TITLE
Theme.Provider Usage Documentation

### ISSUE THREAD

**Issue by PikaJoyce** [twilio-labs/paste#342]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

## Is this related to an existing Paste Component? Please link it here:
[Theme.Provider](https://paste.twilio.design/getting-started/engineering/)

## Describe the functionality you're looking for
Would like a little note on the bottom of the getting started > Usage > Theme.Provider  that says that if you skip this step, your components won't be styled properly. 

Thanks for all of your hard work :)

**Comment by serifluous** [comment]
Thanks, Joyce! Added to our backlog

**Comment by TheSisb** [comment]
Long overdue, but we just merged an update to the Getting Started guides that should address this. Going to close this issue, feel free to reopen if you think it's still unclear.
