### ISSUE TITLE
Headings: use respective variant based on `as` prop

### ISSUE THREAD

**Issue by vnguyen94** [twilio-labs/paste#363]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

## Is this related to an existing Paste Component? Please link it here:
https://github.com/twilio-labs/paste/blob/master/packages/paste-core/components/heading/src/index.tsx

## Describe the functionality you're looking for
hi team, question about the Heading API. I noticed in the first examples in the documentation to use the component like:
```
  <Heading as="h1" variant="heading10">
    Heading One
  </Heading>
  <Heading as="h2" variant="heading20">
    Heading Two
  </Heading>
```
would it be more developer ergonomic that h1 uses the variant  heading10 by default, and so on for the other respective sizes? and you’d be able to override that behavior by explicitly passing in a variant. examples:

general use
```
  <Heading as="h1"> // this now ships with variant="heading10"
    Heading One
  </Heading>
```

with override
```
  <Heading as="h2" variant="heading10"> // this is an override of variant="heading20"
    Heading Two
  </Heading>
```

**Comment by serifluous** [comment]
Thanks! This has been added to our backlog.

**Comment by SiTaggart** [comment]
Hi @vnguyen94 

Thanks for the feedback on the Heading component. For the time being we'll keep this as an item to monitor.

We still feel pretty strongly that the right approach is to decouple the semantic heading level from the visual appearance. We acknowledge that it forces you as a consumer to do a little more work and be explicit in your choices, but we feel that the overall benefit for our uses, particular those who might use screen reader technology, currently outweighs that inconvenience.

I'll be closing this for now, but we'll keep an eye out for any other occurrences of this feedback.
