### ISSUE TITLE
<Button /> Allow more generic data attributes other than `data-test` 

### ISSUE THREAD

**Issue by ghostling** [twilio-labs/paste#368]
We're already using `data-s` as selectors in our unit & e2e tests and would like to keep doing so. 

Noticed that the <Button /> component [only allows `data-test` attribute](https://github.com/twilio-labs/paste/blob/master/packages/paste-core/components/button/src/index.tsx#L97). This is oddly specific/restrictive.

**Comment by SiTaggart** [comment]
Yeah, it is, you're right. The button was one of our first components and since then we've learnt a bunch. 

We generally allow for any applicable global html attribute now on alot of our components, so we should do the same here.

I'll add this to the backlog. Thanks for calling this out.

**Comment by richbachman** [comment]
Hi @ghostling, we just merged a fix for `Button` that allows all standard button attributes, so `data-s` will work.
