### ISSUE TITLE
Chat Message clips text if no spaces were added in the chat composer component

### ISSUE THREAD

**Issue by Viridian-Inc** [twilio-labs/paste#3697]
### Description

When I enter a multi-line message without spaces and submit it, I expect the chat message text will wrap, but the message is clipped.

### Link to Reproduction

https://paste.twilio.design/components/chat-composer

### Steps to reproduce

1. Go to ['chat-composer'](https://paste.twilio.design/components/chat-composer)
2. Scroll down to 'With Chat Log'
3. Enter a multi-line message without spaces in the chat compose component
4. Chat message clips the text to the width of the div

### Paste Core Version

20.7.0

### Browser

Google Chrome

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information
![image](https://github.com/twilio-labs/paste/assets/89794917/74711d2a-9517-403f-9ebc-fb4f804a7893)

_No response_

**Comment by TheSisb** [comment]
The fix will roll out in the next version of Paste. It will be a version higher than current 20.7.0

**Comment by SiTaggart** [comment]
A fix was released in Core v20.8.0
