### ISSUE TITLE
[Docs] Token Lists: Small typo with Font weights

### ISSUE THREAD

**Issue by BtM909** [twilio-labs/paste#3755]
### Description

fontWeightSemibold translates to 600

fontWeightBold also has a value of 600 (should be: 700).

Tokens do translate correctly, so this is only in the documentation:
![image](https://github.com/twilio-labs/paste/assets/957242/cc8de755-37aa-46bd-bb69-1e733ff79484)

### Link to Reproduction

https://paste.twilio.design/tokens/list#heading-font-weights

### Steps to reproduce

1. Go to https://paste.twilio.design/tokens/list#heading-font-weights

### Paste Core Version

20.8.0

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by serifluous** [comment]
Hey @BtM909 ! This is actually intentional in the `twilio` and `twilio-dark` themes to make it simpler to decide between different font weights, and keep the number of fonts we load lean.

**Comment by BtM909** [comment]
Apologies, but maybe I don't understand you correctly. 

So the documentation has 600 for both fontWeightSemibold and fontWeightBold.

But if I use the tokens, the CSS is translated to:

```CSS
// fontWeightSemibold 
.css-e5xzcw  {
    font-weight: 600;
}

// fontWeightBold
.css-e5xzcw  {
    font-weight: 700;
}
```

Besides, the Jest Test also assumes these values:
https://github.com/twilio-labs/paste/blob/33116f9c9ef5211959dd844668c803095d202098/.jest/globals/TestTheme.js#L255C1-L255C17
```JS
 fontWeights: {
    fontWeightBold: "700",
    fontWeightLight: "400",
    fontWeightMedium: "500",
    fontWeightNormal: "400",
    fontWeightSemibold: "600",
  },
```

I hope my comment now makes more sense :)

**Comment by SiTaggart** [comment]
I will add that right now, Flex is using a very old version of the dark theme too, so expect some more differences.

**Comment by BtM909** [comment]
Good to know; we are building on top of Flex (2.0).

Appreciate all your efforts :)
