### ISSUE TITLE
Button vs Button(link-variant) guidance can not be applied

### ISSUE THREAD

**Issue by FirstWhack** [twilio-labs/paste#3759]
### Description

The [Link-Style](https://paste.twilio.design/components/button#link-style-button) Button variant contains the following accesibility warning:

> To reiterate, be mindful when choosing this variant as dictation software users may experience usability issues. Read the guidelines first.

The relevant guidance is:
 > For example, an anchor element will perform its action when clicked and when the enter key is pressed. A Button element will perform its action when clicked and when the enter and spacebar keys are pressed. When holding the control or command key an anchor will open a new browser tab, a Button will not.

> Correctly choosing between an anchor or Button element will help inform A.T. users what will happen next. Will I be taken to an entirely new page or will something happen on the current page?

> Use anchors that look like Buttons sparingly. Voice dictation users may encounter issues when trying to activate them. A user may say, “Click the read more Button”, but the dictation software won’t respond since it can’t tell what the anchor looks like visually. Use an alternative where possible, such as an anchor with an icon or with a larger font size.

None of this guidance is relevant to a Link-Style button variant as a Link-Style Button is still a proper Button, it is not an Anchor.

### Link to Reproduction

https://codesandbox.io/s/paste-starter-template-rz6u3

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Paste Core Version

20

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

There was not an issue type for documentation issues and this isn't really a question.

**Comment by SiTaggart** [comment]
Hi there,

I'm not quite sure if I fully grasp your concerns regarding the guidance provided. Could you clarify or provide more context, so I can better understand?

If I were to summarize it slightly differently to:

> Avoid Link Style buttons. Applying the visual affordance of an Anchor to a Button, might lead your user to think your button element is an anchor, which has very different keyboard interactions and behaviors. Make buttons look like buttons.

Does that make the guidance clearer?

**Comment by FirstWhack** [comment]
@SiTaggart That is more understandable for me personally

**Comment by SiTaggart** [comment]
Correct, sighted users who use keyboard or assistive technologies like pointers or voice dictation, rely on visual appearance of a component to understand how to interact with it.
