### ISSUE TITLE
Spinner component spins off-center on Safari when browser window is zoomed

### ISSUE THREAD

**Issue by apombo-ux** [twilio-labs/paste#3822]
### Description

When I launched Console and navigated around I expected the spinners to behave normally but instead the black spinning part was off center from the underlying grey base.

This is reproducible on the paste documentation site as well, so seems like a Paste issue rather than Console.

It only seems to happen on Safari when the browser is zoomed to something other than 100%. Zooming on Chrome doesn't produce the same issue.

### Link to Reproduction

n/a

### Steps to reproduce

1. Open a Safari browser window
2. Go to ['https://paste.twilio.design/components/spinner'](https://paste.twilio.design/components/spinner)
3. Adjust your browser zoom level to zoomed in or zoomed out from actual size (in the menus that _Safari_ > _View_ > _Zoom in_ / _Zoom out_)
4. Watch the spinner
5. Note that the grey base and black animated spinner have resized inconsistently and the spinner is now spinning off center (see image for an example)

<img width="662" alt="image" src="https://github.com/twilio-labs/paste/assets/98772241/e3788f3d-01e8-4025-af9c-a1aff9600a14">

### Paste Core Version

whichever is on the paste docs site

### Browser

Safari 17.3.1 (19617.2.4.11.12)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by TheSisb** [comment]
Hi @apombo-ux,

Thanks for reporting this issue, I've made a ticket in our backlog to investigate and apply a fix. We will get back to you in this thread when that work is completed.

**Comment by TheSisb** [comment]
I've looked into it a little bit, this seems to be a Safari browser bug with zoom levels and transform-origin.  Found this reference issue on another repo https://github.com/kevinsqi/react-circular-progressbar/issues/101 from a few years ago. Just leaving this note here for now to share the update. It's an edge case issue so should be fine for a few days, but we plan to fix it soon.
