### ISSUE TITLE
Inconsistent Chevron Color in Popover Component on Switching Theme

### ISSUE THREAD

**Issue by batrashubham** [twilio-labs/paste#3828]
### Description

I'm using the Popover component from Twilio Paste in my project and need to switch between light and dark themes based on user interactions. When users switch from the default light mode to dark mode, everything in the Popover changes appropriately except for the chevron, which remains light.

https://github.com/twilio-labs/paste/assets/6443552/ca039a81-8869-4ca4-8b98-9db7b6446bc6

### Link to Reproduction

https://codesandbox.io/p/sandbox/blissful-wu-kyvgfr?file=%2Fsrc%2Findex.tsx

### Steps to reproduce

1. Click on the Popover button.
2. Click on the Switch Theme button.
3. Observe the color of chevron.

### Paste Core Version

20.10.0

### Browser

Google Chrome Version 122.0.6261.94 (Official Build) (arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by TheSisb** [comment]
Hi @batrashubham 

Thank you for reporting this issue. I have found the bug, in that the theme value gets passed down correctly but isn't included in the memo dependency array, and so the arrow wasn't re-rendering. I will push and release a fix soon. Feel free to keep using the popover as-is, and as you update Paste to newer versions it will be resolved.
