### ISSUE TITLE
CodeBlock: Clicking on the copy button throws an error and crashes the Flex app

### ISSUE THREAD

**Issue by andrucz** [twilio-labs/paste#3839]
### Description

When I click on the CodeBlock copy button, this error is thrown and the Flex v1 app crashes:

![Screenshot from 2024-04-01 11-21-31](https://github.com/twilio-labs/paste/assets/2218192/8bf7bfde-46fe-48d6-ab7a-51f4446ccae9)

React version: 16.13.1 (can't use newer versions with Flex v1)

### Link to Reproduction

https://codesandbox.io/p/sandbox/romantic-microservice-zy2py7

### Paste Core Version

20.11.0

### Browser

Google Chrome 123

### Operating System

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by andrucz** [comment]
The recommended fix would have to be applied to the Paste component implementation. Please note that we're using Paste with React 16 due to Twilio Flex v1 constraints.

**Comment by TheSisb** [comment]
Hi @andrucz,

Thank you for the issue report and the reproduction. I have managed to solve the issue and will be releasing a fix in the coming days in the next version of `@twilio-paste/core`.
