### ISSUE TITLE
Modal component footer buttons hitting scrolling body text

### ISSUE THREAD

**Issue by anusha-a2** [twilio-labs/paste#3845]
### Description

When I was evaluating the updated toll-free verification flow on Stage, I noticed the footer buttons sit at the top of the footer rather than aligned to the middle vertically. I asked our devs and they said that's how it appears in code and sent me screenshots. It seems the footer doesn't have a 32px padding on top which is causing the scrolling text in the body to hit the top of the footer where the buttons are. Is that the expected behavior?

<img width="1453" alt="modal footer" src="https://github.com/twilio-labs/paste/assets/148816717/20b2926a-5681-43e2-b59f-3cd41b5dab40">

<img width="1344" alt="footer padding" src="https://github.com/twilio-labs/paste/assets/148816717/18a78786-6508-4907-8327-8b338e69d46c">

### Link to Reproduction

https://8680.previews.console.stage.twilio.com/us1/develop/phone-numbers/manage/incoming/PNbaf9554ba296b4e206c5bbbf98cf88f1/configure?tollfree-verification-modal=true

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Paste Core Version

20.7.0

### Browser

Google Chrome 123.0.6312.87

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by TheSisb** [comment]
Hi @anusha-a2,

Thank you for reporting this issue. This seems like a bug, and I will be making a PR to fix it shortly.

**Comment by TheSisb** [comment]
The fix has merged. It will be released in the next few days in the next patch version of `@twilio-paste/core`. Keep using Modal as-is, and it will be automatically fixed in the near future. Thanks again for the issue report!
