### ISSUE TITLE
Visual Picker Checkbox doesn't work in Firefox when checkbox is clicked on directly

### ISSUE THREAD

**Issue by dangmai** [twilio-labs/paste#3905]
### Description

In Firefox, when I click directly on a checkbox inside a Visual Picker, the selection doesn't change. The selection does change if I click on the box surrounding the checkbox.

### Link to Reproduction

n/a since this is reproducible directly on Paste website

### Steps to reproduce

1. Go to https://paste.twilio.design/components/visual-picker#vertical-checkbox in Firefox
2. Click on any checkbox in the Visual Picker.
3. Notice that no selection is made.

### Paste Core Version

20.2.0

### Browser

Firefox 125.0.3

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by nkrantz** [comment]
Hey @dangmai - thanks for reporting this! I've added a ticket to our backlog to address the bug. We'll let you know here once it's fixed.
