### ISSUE TITLE
Tabs with horizontal line

### ISSUE THREAD

**Issue by pamelahu** [twilio-labs/paste#3913]
### Description

A horizontal line is going through the bottom of the tab.

Example in Paste website:

![image](https://github.com/twilio-labs/paste/assets/18605252/7bb5f166-af63-4166-ae6d-0c68393eb562)

Example with Notification Center that the Console team is trying to develop:

![image](https://github.com/twilio-labs/paste/assets/18605252/f587e13b-d9a9-4dbb-b8ee-6969e5696428)

### Link to Reproduction

https://paste.twilio.design/components/tabs

### Steps to reproduce

1. Visit [Tabs in Paste](https://paste.twilio.design/components/tabs )
2. Zoom in and out at various sizes in the browser; line appears at some zoom %'s

### Paste Core Version

8.2.1

### Browser

Google Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by serifluous** [comment]
Thanks for catching this, @pamelahu ! I've added it to our backlog.
