### ISSUE TITLE
Toast should auto dismiss

### ISSUE THREAD

**Issue by Dhrumil-Mobiuso** [twilio-labs/paste#3936]
### Description

When we launch multiple toast with dismissAfter not all of them gets closed automatically. You can try reproducing it on documentation website itself by adding dismiss after time and click on "AddToast" button multiple times
[screen-capture.webm](https://github.com/twilio-labs/paste/assets/137027961/0f4e0baf-2dae-4037-90df-56e772188dec)
  

### Link to Reproduction

https://codesandbox.io/s/paste-starter-template-rz6u3

### Steps to reproduce

1. Go to Twilio paste documentation in toast section
2. Put dismissAfter time 
3. Click on Add toast button multiple times

### Paste Core Version

20.13.0

### Browser

Google chrome 125.0.6422.142

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by nkrantz** [comment]
Hey @Dhrumil-Mobiuso - thanks for reporting this. I've created a Jira ticket to resolve it and we'll report back when we've finished.

**Comment by Dhrumil-Mobiuso** [comment]
@nkrantz  thank you for the quick response, will be waiting for the bug to be resolved

**Comment by Dhrumil-Mobiuso** [comment]
What is the expected timeline for this issue?

**Comment by serifluous** [comment]
Hey @Dhrumil-Mobiuso, thanks for checking in! We're still investigating the issue, tentatively aiming for a fix by our September release date.

**Comment by Dhrumil-Mobiuso** [comment]
Hey @serifluous , thank you for update, will be waiting for the fix.

**Comment by serifluous** [comment]
Hey @Dhrumil-Mobiuso ! This fix will be merged in with this PR: #4050

**Comment by Dhrumil-Mobiuso** [comment]
Thank you for update @serifluous

**Comment by krisantrobus** [comment]
Hi @Dhrumil-Mobiuso , this fix has now been released in our latest version of @twilio-paste/core 20.16.0
