### ISSUE TITLE
Table stickyHeader has a conflicting zIndex

### ISSUE THREAD

**Issue by Jonathan-Dilks-at-Wrisk** [twilio-labs/paste#3939]
### Description

When using Flex 2.7's Status Report `Twilio-SideNav`, they share the same zIndex of 10, so the table header ends up obscuring the close button of the Status Report SideNav dialog.

### Link to Reproduction

Unable to reproduce within code sandbox, as this needs to be done in a Twilio Flex environment.

### Steps to reproduce

1. Make a 100% height and width Paste Table with a Sticky Header `stickyHeader` prop enabled.
2. Use this within Twilio Flex in a full-screen `View` (e.g. `Flex.ViewCollection.Content.add(<Flex.View` ....)
3. Open the Status Report dialog whilst in this view and observe the glitch.

### Paste Core Version

20.12.0

### Browser

Chrome 125

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Jonathan-Dilks-at-Wrisk** [comment]
Overriding `THEAD` to a zIndex of 9 indeed fixes this, but of course that isn't a Paste design Token option nor the default z-Index for a stickyHeader Table Header.

**Comment by Jonathan-Dilks-at-Wrisk** [comment]
[xf](https://github.com/twilio-labs/paste/blob/ccabf8da7139c5b8d5ac55cffe55907925e7488f/packages/paste-core/components/table/src/THead.tsx#L13) I can see the current Paste library uses a zIndex of 10 here.

**Comment by nkrantz** [comment]
Hey @Jonathan-Dilks-at-Wrisk - just an update that we're taking a look at this and working on a solution. We'll update here once we've made some progress.

**Comment by nkrantz** [comment]
Hey @Jonathan-Dilks-at-Wrisk - you should be able to adjust the zIndex of your SideNav using this code:

```
manager.updateConfig({
  theme: {
    componentThemeOverrides: {
      SideNav: {
        Container: {
          zIndex: 20 // or as high as your app requires
        }
      }
    }
  }
});
```

Let me know if that solves your issue.

**Comment by Jonathan-Dilks-at-Wrisk** [comment]
Hi @nkrantz that's another good workaround, which means we don't have to change the Paste zIndex! It would be nice to know if this zindex change could eventually be pulled into a Flex UI 2.x release ?

**Comment by nkrantz** [comment]
@Jonathan-Dilks-at-Wrisk good question! To make that request to Flex UI, please reach out to support by navigating to console.twilio.com, clicking on Docs and Support and selecting Help Center. Thanks!
