### ISSUE TITLE
<Button+Icon> Documentation is missing `size` attribute in example code

### ISSUE THREAD

**Issue by ramoneguru** [twilio-labs/paste#395]
**Describe the bug**
On the button section with icons, the `size` attribute is missing from the example.
https://paste.twilio.design/components/button/#icon-only-button

**To Reproduce**
1. Go to the buttons+icons section.
2. Try to copy/paste the button+icon code.
3. Compiler/linter will complain that the required `size` attribute is missing.

**Expected behavior**
Copy/pasting the icon code should have no missing required attributes.

**Comment by SiTaggart** [comment]
Yeah it's definitely a thing that occurs more than it should. We have an unusual situation where we write the docs in mdx, and the code blocks are essentially well formatted strings that get executed. Problem is typescript doesn't think their code, so we get none of the warning in IDE or compilation. It's frustrating. 

If you come across a way to get mdx content through typescript compilation I'm all ears, though. Been searching and I've got nothing so far.

As for that particular example, I'll get a ticket up to make the changes. Thanks for the feedback!

**Comment by TheSisb** [comment]
Appears to be fixed. Closing.
