### ISSUE TITLE
Twilio-paste/styling-library emotion css add a body color to rgb(241, 241, 241)

### ISSUE THREAD

**Issue by link2malkeet** [twilio-labs/paste#3988]
### Description

I am using @twilio-paste/core for using UI components, and it happens to add the following styles to the html head
<style data-emotion="css-global"></style>
<style data-emotion="css"></style>
These are empty tag and eventually updates the html "body" background to rgb(241, 241, 241)

It is coming from twilio paste package but I am still not sure what exact component causing it.

There is "stackoverflow" thread about the same without any resolution
https://stackoverflow.com/questions/58644786/which-components-are-adding-emotion-css-global-styles

Alternatively, we have to override the body background color, which is not great.

So can you please fix this, it should not really add any global style by default.

Thanks

### Link to Reproduction

https://codesandbox.io/s/paste-starter-template-rz6u3

### Steps to reproduce

1. Go to https://codesandbox.io/s/paste-starter-template-rz6u3
2. Check the app body tag 
3. Check the 'Calculated' "backgound-color" which is set by "style" tag (there should not be any globalStyle)

### Paste Core Version

10.20.0

### Browser

126.0.6478.127

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by serifluous** [comment]
Hey @link2malkeet ! Can you share a screenshot of what you're seeing? We can't reproduce the exact RGB value you're seeing, so I just want to make sure we're looking at the same thing.

**Comment by krisantrobus** [comment]
Hi @link2malkeet are you still facing this issue or has this been resolved? We attempted to reproduce this but our team saw different RGB values.
