### ISSUE TITLE
Having issues with the Abstract paste components library

### ISSUE THREAD

**Issue by elo69018** [twilio-labs/paste#404]
Hi,
I'm not sure this is the right place for this, but I reached out to a Twilio support agent and they said to open an issue here. I need access to the Paste components library in Abstract and requested access to it a couple days ago. Someone was able to grant me access and I successfully synced the project to Abstract. However, a few hours later the project disappeared - I don't see anything in Abstract anymore. Could I have some assistance with this issue? Thanks!

**Comment by SiTaggart** [comment]
Can I ask what you need this for, @elo69018?

**Comment by elo69018** [comment]
Hi @SiTaggart - I'm a product designer building a Twilio Flex app for my client and am looking for the right design system to use.

**Comment by SiTaggart** [comment]
Hi @elo69018 Flex currently doesn't use Paste. I'd suggest you reference the Flex UI documentation found here https://www.twilio.com/docs/flex/ui
