### ISSUE TITLE
Textarea - Height not customizable

### ISSUE THREAD

**Issue by fred-croix** [twilio-labs/paste#4064]
### Description

When attempting to customize the height of the textarea widget, the height is forcibly set to 76px using `76px !important`. This prevents users from adjusting the height to their desired value, such as 16px for a single-line textarea.

### Link to Reproduction

https://paste.twilio.design/components/textarea

### Paste Core Version

20.15.0

### Browser

Chrome, Firefox

### Operating System

- [x] macOS
- [x] Windows
- [x] Linux

**Comment by serifluous** [comment]
Hey @fred-croix ! You can set a max height on Textarea using the `maxRows` prop: https://paste.twilio.design/components/textarea#resizable-textarea

Let us know if that helps solve your issue.

**Comment by krisantrobus** [comment]
Hey @fred-croix, I hope this solution worked for you! I will close this issue out but if you're still having problems we can always reopen.
