### ISSUE TITLE
docs: incorrect $font-size-base value

### ISSUE THREAD

**Issue by dimitri-kandassamy** [twilio-labs/paste#4117]
### Description

When I looked up the documentation for`$font-size-base` design token I expected to find a value of 16px whereas I saw 100% and 1600px. 

### Link to Reproduction

https://paste.twilio.design/tokens/list#font-sizes

### Steps to reproduce

1. Go to https://paste.twilio.design/tokens/list#font-sizes
2. Scroll down to $font-size-base
3. Observations: `value: 100%, altValue: 1600px`
4. Expected: value: `1rem, altValue: 16px` 

<img width="829" alt="Screenshot 2024-10-22 at 18 09 56" src="https://github.com/user-attachments/assets/8d44e366-dbaa-4d06-8563-dc6a3131f8c8">

[token definition in the code](https://github.com/twilio-labs/paste/blob/012fc44f1c5f99e1a5713a87b3fae1175dd1f9a0/packages/paste-design-tokens/tokens/global/font-size.yml#L8)

### Paste Core Version

20.16.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by serifluous** [comment]
Thanks for catching this @dimitri-kandassamy ! We've added a ticket for this in our backlog to fix the calculation here: https://github.com/twilio-labs/paste/blob/636a48d135d25825a30db46878240bd3b50d01a8/packages/paste-theme/src/utils/remToPx.ts#L10

**Comment by serifluous** [comment]
Thanks for reporting this! This is now fixed.
