### ISSUE TITLE
Padding in card component unclear from built-in grid

### ISSUE THREAD

**Issue by Angelangg** [twilio-labs/paste#423]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
1. The padding in the card component shown with the grid override changes as you expand and contract the card.
2. There's no way to see how much the padding is from the component itself.

**To Reproduce**
1. Insert the card component in Sketch. Card > console > card
2. In overrides, select grid & spacing > grid > any option
3. Expanding and contracting the card component causes the padding amount to change.

**Expected behavior**
I expect the padding to stay the same with expansion and contraction and the inner grid to expand/contract.

I expect to be able to inspect the amount of padding that is added to the card component especially when I am adding other components inside the card.

**Screenshots**

**Desktop (please complete the following information):**
This is in Sketch Version 64 (93537)

**Additional context**
None

**Comment by serifluous** [comment]
@Angelangg Thanks!

1. Is the padding change still happening for you when you resize the card symbol? Can you link to an Abstract artboard with the issue, if so?

2. We recently added a "card anatomy" symbol into the Sketch library. Could you share some thoughts about whether that helps you at all. If you have ideas on how you'd expect or want to see the padding within a component, please share, too!

**Comment by Angelangg** [comment]
@serifluous 
1. Nope, it's perfect now!
2. Yes, I love this!! Thank you for explaining the technical side of the calculations. Appreciate it.
