### ISSUE TITLE
Clarify how the padding in the card example is calculated

### ISSUE THREAD

**Issue by Angelangg** [twilio-labs/paste#424]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
The padding in the card example is not a multiple of 4 and therefore I am confused about what the default padding should be.

**To Reproduce**
1. Insert the card component in Sketch. Card > console > example > basic with buttons
2. Detach from symbol to inspect the card padding
3. The card padding says 22px, which is not a multiple of 4

**Expected behavior**
I expect the padding to be a multiple of 4 and if not, there should be some explanation somewhere that explains why not. 

**Screenshots**

**Desktop (please complete the following information):**
This is in Sketch Version 64 (93537)

**Additional context**
None

**Comment by serifluous** [comment]
(c/p from #423)

We recently added a "card anatomy" symbol into the Sketch library. Could you share some thoughts about whether that helps you at all. If you have ideas on how you'd expect or want to see the padding within a component, please share, too!
