### ISSUE TITLE
"To Do" and the "Avoid" uses the same image

### ISSUE THREAD

**Issue by JT1989** [twilio-labs/paste#451]
**Describe the bug**
The "Do" and "Avoid" images are the same. 

**To Reproduce**
1. Go to https://paste.twilio.design/icon-system/#give-informative-icons-a-title

**Expected behavior**
As a designer who is here to quickly scan the images, I expect to see two different images between the "Do" versus "Avoid." Because the visual cues use the same image, I'm confused on what to do versus what to avoid

**Screenshots**
<img width="768" alt="Screen Shot 2020-05-18 at 3 37 21 PM" src="https://user-images.githubusercontent.com/8630856/82266078-89030800-991d-11ea-8042-c65df6b0dc27.png">

**Desktop (please complete the following information):**
 - OS: ios
 - Browser chrome

**Comment by TheSisb** [comment]
Hi JT,

Thanks for the ticket! While I don't necessarily think this is a bug, I can see that having live components in some Do/Avoids while having images in others is confusing to readers that quickly scan through the content. This particular example is trying to showcase a long-hover effect, which isn't something you can perceive without user interaction or a screen-reader.

The solution here may just be as simple as swapping the component out for an image, but we need to consider future effects and designs. We're going to noddle on this.

**Comment by JT1989** [comment]
Thanks @TheSisb! Happy to call it something else since this isn't a bug. 

I left this section feeling confused and thought it was the images. I read it over a few times, but to no avail. Maybe I'm just not technical enough or need someone to educate me through in person training to understand the concept.  

If you have suggestions on other literature to better understand on what "give informative icons" means, before & after and the why behind, that'd be great.

**Comment by TheSisb** [comment]
Fixed in https://github.com/twilio-labs/paste/pull/1303
