### ISSUE TITLE
Can't click on "Console" or Search because the BLM banner is blocking it. 

### ISSUE THREAD

**Issue by JT1989** [twilio-labs/paste#490]
**Describe the bug**
Can't click on Console. Can't Search.

**To Reproduce**
- Go to https://paste.twilio.design/components/alert#neutral
- Go to https://paste.twilio.design/components/button#examples
- Go to https://paste.twilio.design/components/paragraph#composition-notes

**Expected behavior**
You should be able to click on **Console**.
You should be able to search.
Keep the BLM banner. Recommend moving it on top of the Paste website.

**Screenshots**
<img width="1440" alt="Screen Shot 2020-06-08 at 9 54 18 AM" src="https://user-images.githubusercontent.com/8630856/84058527-393cbd00-a96e-11ea-9d01-2fe39c1c93ee.png">

**Desktop (please complete the following information):**
 OS

**Comment by serifluous** [comment]
Thanks for finding this! I've added a ticket for us to look into it and fix.

**Comment by TheSisb** [comment]
I've opened a PR to address this issue: https://github.com/twilio-labs/paste/pull/488
I'll try to get it merged later today

**Comment by TheSisb** [comment]
Should be fixed now, please let us know if it still happens for you
