### ISSUE TITLE
Theme.Provider "window.matchMedia is not a function"

### ISSUE THREAD

**Issue by andipants12** [twilio-labs/paste#499]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
Seeing this error when trying to use the newest version of `Theme.Provider`, [looks like it's coming from the added animation utilities](https://github.com/twilio-labs/paste/commit/2cbe91982af27be4b3fccc62e3280b49a0f50539#diff-5ba736f7132516e7668bf069bb83143d).  Only seeing this issue when running our test suite, not running in the Console.

**To Reproduce**
1. Using most recent releases of `Theme.Provider` and `react-testing-library` create a mocked test component wrapped in the `Theme.Provider`.
2. Get the error in the terminal.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome

**Additional context**

**Comment by TheSisb** [comment]
Hi @andipants12,

Looks like this was an oversight. I've added a ticket to our backlog to address this soon.  Thanks for reporting it!

**Comment by andipants12** [comment]
Awesome, thank you so much!

**Comment by TheSisb** [comment]
This issue auto-closed when I merged my branch. Please feel free to re-open if it didn't fix your issue when you upgrade to the latest version of Theme/Modal/Animation-lib

**Comment by andipants12** [comment]
Sounds good, thank you @TheSisb!
