### ISSUE TITLE
Grid + Column, cannot map to create children.

### ISSUE THREAD

**Issue by andipants12** [twilio-labs/paste#500]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
Really not sure what the root cause of this is, but `Grid` does not seem to accept mapped `Grid` and `Column` children.

**To Reproduce**
See this [CodeSandbox](https://codesandbox.io/s/sweet-sunset-sev1s?file=/src/Grid.js), notice that when mapped, the styling has a bug, when not mapped, the layout is fine.

**Expected behavior**
Should match the behavior indicated in the non-mapped components.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome

**Additional context**
n/a

**Comment by andipants12** [comment]
[
<img width="769" alt="Screen Shot 2020-06-11 at 2 34 52 PM" src="https://user-images.githubusercontent.com/18120906/84441489-c131f980-abf0-11ea-8520-b3c1e8b76034.png">
](url)

**Comment by richbachman** [comment]
Hi @andipants12 I think the fragment `<>` in your mapped map was throwing off the styling. The width was being applied to that. We're cloning the `Grid` children so maybe that is doing something weird with the fragment. I moved the `Column` out of the `additionalFeaturesRow` and into the map. Here's a codesandbox link: https://codesandbox.io/s/focused-chandrasekhar-16wh1?file=/src/Grid.js

**Comment by andipants12** [comment]
Awesome, thank you!

**Comment by andipants12** [comment]
Going to close this, thanks again!
