### ISSUE TITLE
Using `gutter="space30"` getting design token error with <Grid />

### ISSUE THREAD

**Issue by andipants12** [twilio-labs/paste#504]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
Getting an error `Failed prop type: [Box]: invalid prop supplied "marginRight=-0.5rem", expected a token value.`
Looks like that corresponds to `space30`, which as indicated by the docs, is a valid value for `gutter` prop on `<Grid />`.

**To Reproduce**
using the following version of Paste libraries:
```
    "@emotion/core": "10.0.28",
    "@emotion/styled": "10.0.27",
    "@styled-system/theme-get": "5.1.2",
    "@twilio-paste/animation-library": "0.2.0",
    "@twilio-paste/core": "2.10.3",
    "@twilio-paste/design-tokens": "5.2.1",
    "@twilio-paste/dropdown-library": "0.1.1",
    "@twilio-paste/icons": "2.2.3",
    "@twilio-paste/reakit-library": "0.3.0",
    "@twilio-paste/style-props": "1.2.0",
    "@twilio-paste/theme": "3.2.1",
    "@twilio-paste/theme-tokens": "3.1.2",
    "@twilio-paste/types": "3.0.8",
```

Create a <Grid /> and use `gutter="space30"`, you will see that error in the console terminal.

**Expected behavior**
Should not show error in console terminal.

**Screenshots**
<img width="1402" alt="Screen Shot 2020-06-13 at 2 58 51 PM" src="https://user-images.githubusercontent.com/18120906/84579922-f5d7b980-ad86-11ea-9f65-156441e6f008.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome

**Additional context**
n/a

**Comment by andipants12** [comment]
Hi there team, still getting this error after updating all paste dependencies to the most current version. Has this been reported by other folks?

**Comment by richbachman** [comment]
Hey @andipants12. This is the a known issue with Grid and our prop validator function. The function doesn't like the negative value versions of our tokens, which we need for the column gutters. I'll add a ticket to our backlog, so we can work through the issue.

**Comment by TheSisb** [comment]
@richbachman appears to have fixed this now in https://github.com/twilio-labs/paste/pull/591
Let us know if you still have any issues!
