### ISSUE TITLE
Under Tokens > Border Colors, "borderr"

### ISSUE THREAD

**Issue by katrina-lindholm** [twilio-labs/paste#53]
$color-border-successSuccess **borderr** color | #00994A |  
$color-border-success-lightestLightest success **borderr** color | #E0FFEF |  
$color-border-warningWarning **borderr** color | #E46216 |  
$color-border-warning-lightestLightest warning **borderr** color

**Comment by TheSisb** [comment]
Thanks for the issue report! 😃  I just merged a PR to correct the typo.  It will be live on our website within the next 10 minutes.
