### ISSUE TITLE
Conflicting peer dependencies

### ISSUE THREAD

**Issue by margusha** [twilio-labs/paste#538]
When doing installation based on paste install instructions, peer dependencies seem to be out of sync.

**To Reproduce**
install all the neccessary dependencies with following command:

`yarn add react@^16.8.6 react-dom@^16.8.6 prop-types@^15.7.2 react-uid@^2.2.0 @twilio-paste/types@3.0.10 @twilio-paste/style-props@1.2.6 @twilio-paste/design-tokens@5.3.0 @twilio-paste/theme@3.2.6 @twilio-paste/icons@2.3.0 @twilio-paste/styling-library@0.1.0 @twilio-paste/animation-library@0.2.1 @twilio-paste/dropdown-library@0.1.1 @twilio-paste/reakit-library@0.6.0 @twilio-paste/core@2.14.2`

**Expected behavior**
none of the paste components has unmet peer dependency issues

**Desktop (please complete the following information):**
 - OSX
 - no browser involved, installation from command line

**Additional context**
seems that some of the packages in @twilio-paste/core have inconsistent peer dependencies. e.g. modules require multiple versions of reakit-library to be installed. here's the output:

```
error "@twilio-paste/core#@twilio-paste/disclosure-primitive#@twilio-paste/reakit-library@^0.5.0" doesn't satisfy found match of "@twilio-paste/reakit-library@0.6.0"
error "@twilio-paste/core#@twilio-paste/menu-primitive#@twilio-paste/reakit-library@^0.5.0" doesn't satisfy found match of "@twilio-paste/reakit-library@0.6.0"
error "@twilio-paste/core#@twilio-paste/screen-reader-only#@twilio-paste/styling-library@^0.0.0" doesn't satisfy found match of "@twilio-paste/styling-library@0.1.0"
error "@twilio-paste/core#@twilio-paste/tabs-primitive#@twilio-paste/reakit-library@^0.5.0" doesn't satisfy found match of "@twilio-paste/reakit-library@0.6.0"
error "@twilio-paste/core#@twilio-paste/tooltip-primitive#@twilio-paste/reakit-library@^0.5.0" doesn't satisfy found match of "@twilio-paste/reakit-library@0.6.0"
error "@twilio-paste/core#@twilio-paste/truncate#@twilio-paste/styling-library@^0.0.0" doesn't satisfy found match of "@twilio-paste/styling-library@0.1.0"
```

**Comment by TheSisb** [comment]
Added to our backlog to investigate.  Do you have the same issue if you don't specify the version numbers in your `yarn add` command?

**Comment by SiTaggart** [comment]
I looked at this yesterday too but forgot to post. I don't really know how it's possible but there is a weird out of sync problem with the package.json files on some of these packages.

compare

https://github.com/twilio-labs/paste/blob/master/packages/paste-core/primitives/menu/package.json 

```
"peerDependencies": {
    "@twilio-paste/reakit-library": "^0.6.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
  "devDependencies": {
    "@twilio-paste/reakit-library": "^0.6.0"
  }```

to

https://unpkg.com/browse/@twilio-paste/menu-primitive@0.1.5/package.json
```
"peerDependencies": {
--
31 | "@twilio-paste/reakit-library": "^0.5.0",
32 | "react": "^16.8.6",
33 | "react-dom": "^16.8.6"
34 | },
35 | "devDependencies": {
36 | "@twilio-paste/reakit-library": "^0.6.0"
37 | },
```

I don't even know how the peer and dev dep remain out of sync...

**Comment by margusha** [comment]
the issue comes from @twilio-paste/core itself. some of the components require different versions of peer dependencies. I have a gut feeling that during the publish to npm, something gets out of sync. I tried to compare what gets installed and what's in github and these seem to be different. I've noticed it for a while, will grab one slack message from few weeks ag. the pattern seems still be the same:

`what i’m seeing is that npm provides wrong version. disclosure primitive was released in sequence with short time frame, 0.1.0 and 0.1.1.
0.1.0 had peerDependency for reakit-library@0.1.0
and 0.1.1 had peerDependency for reakit-library@0.2.0.
somehow in npm repo 0.1.1 still contains reference to reakit-library@0.1.0`

**Comment by margusha** [comment]
any updates on this?

**Comment by SiTaggart** [comment]
Not as yet @margusha, we've been super heads down on UDL and console nav deliverables so it hasn't been prioritized yet. Hopefully we'll get to look at it after this sprint finished

**Comment by SiTaggart** [comment]
Hey @margusha, having done a recent fresh create-react-app install, I'm not seeing these unmet dependency version warnings any more. Is that the same case for you?
