### ISSUE TITLE
Responsive heading variants not working as intended

### ISSUE THREAD

**Issue by aayushpi** [twilio-labs/paste#539]
Discovered this issue while using headings with responsive variants:

# When using responsive variants:

`      <Heading as="h1" variant={["heading60","heading60","heading10"]}>
        Some text here
      </Heading>`

Desktop:

![image](https://user-images.githubusercontent.com/2206776/85953684-1a0acd00-b927-11ea-94cf-46ef3379016b.png)

Tablet:

![image](https://user-images.githubusercontent.com/2206776/85953692-27c05280-b927-11ea-9567-3a8f6d35082b.png)

Mobile:

![image](https://user-images.githubusercontent.com/2206776/85953701-37d83200-b927-11ea-85ee-7698fc2cb3b8.png)

# When !using responsive variants:

`<Heading as="h1" variant="heading10">
    Some text
</Heading>`

![image](https://user-images.githubusercontent.com/2206776/85953749-72da6580-b927-11ea-9044-102ed0722e47.png)

----

My hunch, looking at the code is that the variants are responding to the array, but **not to all indexes of it**.

**Comment by SiTaggart** [comment]
It was never built to take responsive variants, and I’m not sure it should to be honest. 

Our styled components should have a level of in built opinion on how things scale across breakpoints. Our type ramp shouldn’t be different. 

If we have clear opinions of how to create appropriate space, rhythm, and hierarchy with headings, paragraph and list styles, then we should have opinions on how that scales on different screen sizes to give the most optimum experience for our typography.

If you want greater control over that, then you can drop to the Text primitive and set your own sizes across the breakpoints.
