### ISSUE TITLE
Underlining on buttons seems like overkill

### ISSUE THREAD

**Issue by Matjaxon** [twilio-labs/paste#54]
I personally find the added underlining on hovered buttons to be unnecessary and jarring.  The buttons already change color and have a pointer change.  I understand that the underlining was added for accessibility but wouldn't that already be sufficiently covered by the pointer change?

**Comment by serifluous** [comment]
Thanks so much for the feedback! We'll take this into account when we iterate next on buttons and discuss with product design teams across Twilio.

For more accessibility context, the pointer change itself won't be sufficient when you're navigating a page with a keyboard only, for example. If you'd like to learn more about our accessibility considerations, definitely let us know. We love talking about accessibility with teams.

You're welcome at office hours any time to discuss this more, too.

**Comment by Matjaxon** [comment]
I took the screenshot below after tabbing through the paste docs page.  Chrome (I'm assuming?) already seems to offer outlining of the active element.

<img width="781" alt="Screen Shot 2019-08-21 at 9 43 21 AM" src="https://user-images.githubusercontent.com/7808060/63451043-303b2900-c3f8-11e9-94a7-157a3716001f.png">

I would assume there's similar browser support or plugins to address this need better than us adding additional underlining.

**Comment by TheSisb** [comment]
Hey @Matjaxon, a delayed update but we are going to remove the underlines from Buttons.  Will circle back when that PR is in.

**Comment by Innovator007** [comment]
I would like to work on this if its open

**Comment by SiTaggart** [comment]
Thanks for your interest @Innovator007, but I'll be tackling this today
