### ISSUE TITLE
Tooltip: useTooltipPrimitiveState baseId property should be mandatory

### ISSUE THREAD

**Issue by tomtobac** [twilio-labs/paste#548]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
if there is no `baseId` is generated randomly and that causes that any snapshots fails every time is executed.

**To Reproduce**
1. Use Tooltip primitive
2. Do not pass `baseId`
3. Create a snapshots.
4. Run again the test and we should see another id

**Expected behavior**
IMO `baseId` should be mandatory and maybe the since it's setting `aria-describedby` maybe should a descriptive for the tooltip

**Screenshots**
![image](https://user-images.githubusercontent.com/10562610/86359873-de973800-bc71-11ea-83fe-7a838b8f5b8d.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version 83.0.x

**Additional context**

**Comment by SiTaggart** [comment]
Hi @tomtobac 

Thanks for posting. If you set your own baseId, does that solve you're problem?

```
const tooltip = useTooltipPrimitiveState({placement: 'right', baseId: 'base-tooltip-id'});
```

**Comment by tomtobac** [comment]
yes, it does, but it wasn't clear to me that it was randomly generated that why I think that if we make it mandatory it will solve future problems

**Comment by SiTaggart** [comment]
I'd be cautious about making it mandatory as there's no requirement to do so as it's not like it breaks if you don't. It does what is expected of it, which is generate unique ids as these cannot clash inside a single page.

What we might need to do is make it clearer in components that _do_ auto generate ids, that it occurs and to be mindful of that when creating snapshot tests.

I am curious what you are testing for in that snapshot test, though. Do you mind sharing with us the intention?

**Comment by tomtobac** [comment]
Well, my intention is just to have a quick unit test using snapshot which renders a table and inside this table we have this tooltips.

By the way, I tried to use the new `<Tooltip />` and I go some problems as well:

1) Using only an Icon as children didn't display the tooltip when I hover it. I sort it wrapping it with a `<Box />`
```tsx
			<Tooltip text={msg}>
				<InformationIcon decorative={true} size="sizeIcon30" />
			</Tooltip>
```
2) The default style (white) has a line between the box and the tooltip arrow
![image](https://user-images.githubusercontent.com/10562610/86620697-0f060b80-bfbd-11ea-9dc7-e0abcfa33a24.png)

3) I would like to style it as black and text white, as we have in console, but im not able to set any color because of the types
![image](https://user-images.githubusercontent.com/10562610/86620799-4a083f00-bfbd-11ea-9cf0-13b9c9827206.png)

**Comment by SiTaggart** [comment]
> Using only an Icon as children didn't display the tooltip when I hover it.

That's expected behaviour. As per the documentation tooltips should only be placed on Focusable elements like buttons and anchors. https://paste.twilio.design/components/tooltip#focusable-element. I am about to update that documentation to make it much more explicit though. Please replace the `Box` with either a `Button` or an `Anchor`.

> The default style (white) has a line between the box and the tooltip arrow

We aren't seeing it on our implementation, so I'm assuming that something in Console might be doing this. Is this on Stage or Dev where we can inspect?

> I would like to style it as black and text white, as we have in console

Please follow the Paste design for tooltips. We are moving away from white on black tooltips.

> When I tried to use the new tooltip using tests I found out that there are some failed proptypes into `TooltipArrow`

Do you have a better error message? It doesn't actually show what prop is failing or what the value is.

**Comment by tomtobac** [comment]
Ok, thanks for the quick answer @SiTaggart :)

If add an anchor (which is mandatory the href) or a button I can not achieve the feel and lock of the previous tooltip on the icon...  I will keep the default styles as white.

I will try to have tomorrow (18:00 CEST) on stage and I will let you know through slack if you wanna check :)

Here you can see better the error:
```bash
 Error: Uncaught [TypeError: Cannot read property 'fontSize70' of undefined]
```
I guess this is coming from `<TooltipArrow />`
![image](https://user-images.githubusercontent.com/10562610/86632850-331f1800-bfd0-11ea-93bb-3641b5428190.png)

**Comment by richbachman** [comment]
Hi @tomtobac. For your tests, you'll need to wrap your test with our `Theme.Provider`.

**Comment by richbachman** [comment]
Hi @tomtobac. We just merged a fix for the Tooltip arrow, so that line shouldn't appear above it anymore. Once you've updated the package, you should be good to go.
