### ISSUE TITLE
Paste website search toolbox breaks the webpage if ESC is pressed

### ISSUE THREAD

**Issue by tomtobac** [twilio-labs/paste#549]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**

**To Reproduce**
1. Go to https://paste.twilio.design/
2. Click on Combobox (jump to)
3. Search for anything
4. Press `ESC` 
5. Page is totally blank

**Expected behavior**
Close the combobox and keep the page in the same state.

**Screenshots**
![image](https://user-images.githubusercontent.com/10562610/86361425-1bfcc500-bc74-11ea-9056-d3a57d0e3434.png)
![image](https://user-images.githubusercontent.com/10562610/86361450-2b7c0e00-bc74-11ea-8829-11b28abbffe6.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version 83.0.x

**Additional context**

**Comment by tomtobac** [comment]
Also it doesn't find the tooltip primitive the search box :(

**Comment by richbachman** [comment]
Hi @tomtobac. Thanks for bringing this to our attention. I'll get a ticket in to fix the search escape error. As for the tooltip primitive, we're a little behind in our search indexing, and have a ticket in place to get that updated as well.

Also note, we should be launching our styled tooltip component later today.

**Comment by SiTaggart** [comment]
The escape key bug is now fixed. The indexing of new content is not, but that wasn't the main focus of this issue.
