### ISSUE TITLE
Twilio Bootstrap styles conflict on <legend /> element

### ISSUE THREAD

**Issue by ghostling** [twilio-labs/paste#556]
**Current behavior**

Currently observing this when using `<RadioGroup />` component. Twilio Bootstrap adds a bottom border to the "To get started choose" text below: 
![image](https://user-images.githubusercontent.com/2553665/86823175-6057de80-c041-11ea-81ad-04c816f3250e.png)

**Expected behavior**
No border.

**Comment by richbachman** [comment]
Hi @ghostling. We just published a fix for this. If you update the forms package to the newest version, you should be good to go. Let us know if you have any other issues.

**Comment by ghostling** [comment]
Thanks @richbachman ! It works perfectly.
