### ISSUE TITLE
Button as Anchor

### ISSUE THREAD

**Issue by elainelylee** [twilio-labs/paste#57]
The documentation states that the recommendation is "Try not to use anchors that look like buttons."  And, "Only one primary button should be used on each screen so users are clear about what the intended action is."

There will be use cases where the primary action navigates to another page. Traditionally, this is the call to action but the action is taken place on another page for example. Foreseeing that our console will have pages like these that seem like marketing pages or gates, what's the recommendation here regarding using a button or an anchor?

**Comment by serifluous** [comment]
Thanks, Elaine! I'll be working on some guidelines over the next two weeks to address this. Definitely let us know if you notice anything else missing or confusing in them (even the smallest things).

**Comment by serifluous** [comment]
Needs more refinement based on feedback during office hours, especially what a good alternative is.
