### ISSUE TITLE
Error text color in Paste is different from design library

### ISSUE THREAD

**Issue by elainelylee** [twilio-labs/paste#585]
If the design library version is incorrect, can we update the design library?

**Comment by serifluous** [comment]
Good catch, thank you! Yes, you can update the design library. Create a branch in the console theme Sketch file and tag any of the DSYS designers as a reviewer.

**Comment by elainelylee** [comment]
To confirm, are you saying that the Paste color for error text is correct and the one in Sketch is NOT correct? Sketch has many error/destructive red variations. If we are changing the error text red in Sketch, that means we will also need to change the darker, dark, light versions. If so, need confirmation that Paste is correct and design library isn't, meaning I'll copy over the values from Paste to Sketch.

**Comment by serifluous** [comment]
The layer styles in Sketch that start with "color-text-error" are incorrect.

`link-destructive` looks right to me, but the dark/darker ones don't. We'll have to do some digging into why that is. Can you make the changes to just `color-text-error`?

If the other discrepancies in color are urgently affecting the work you're doing, let us know.
