### ISSUE TITLE
Button Color Scheme

### ISSUE THREAD

**Issue by andelopes** [twilio-labs/paste#59]
- The blue and red colors used for primary and destructive buttons feel very deep and saturated. Together they make a very stylized theme that feels dated and heavy.
- The contrast between the primary and secondary/destructive buttons is jarring. It feels like an over-optimization for usability and draws far too much attention to the primary button and away from the others. In general, I feel like it makes groupings / interfaces harder to parse bc the contrast is so high.

**Comment by andelopes** [comment]
- The button outline animation is similarly too dark, and the fact that it does not disappear makes the button as an element seem too lineated/busy, especially with the text underline.
![image](https://user-images.githubusercontent.com/14846448/63195810-7f641100-c028-11e9-8738-596382ebb567.png)

**Comment by serifluous** [comment]
Thanks so much for the feedback! We'll take this into account when we iterate next on buttons and discuss with product design teams across Twilio.

When you have the time:
- Can you provide examples you've seen of buttons that seem more usable and some reasons why?
- Can you expand a bit on the button outline animation (_e.g._, how you'd expect it to appear or work)? We want to refine the transition animations in later releases, so any more detail here would be great!

**Comment by serifluous** [comment]
Following up here: we realized that as we've been aligning console and SendGrid colors, there have been some bugs in the colors we've used for the button interaction states, so just wanted to acknowledge that, too 👌

**Comment by aayushpi** [comment]
Test comment to see if it shows up on Github

**Comment by andelopes** [comment]
Thanks for following up. The primary inactive / unselected blue looks great now!

The animation seems a lot more refined as well, given that the outline for the primary button is now inside the shape of the button. It feels more like a physical button now.

Might be a micro-optimization, but I still feel the active / selected outlines for the secondary and destructive buttons are a tad too dark and don't feel as cohesive with the primary action. Further, the destructive button itself gets really colored and deeply red, so it doesn't feel cohesive with the secondary buttons.

![image](https://user-images.githubusercontent.com/14846448/63977259-33718d00-ca68-11e9-9e2b-2abe58015338.png)
![image](https://user-images.githubusercontent.com/14846448/63977377-89463500-ca68-11e9-8918-0935dc2e74e6.png)

In my mind, the active / selected blues would be the same in the primary and secondary buttons.
![image](https://user-images.githubusercontent.com/14846448/63978134-7e8c9f80-ca6a-11e9-89bd-552877476993.png)

**Comment by aayushpi** [comment]
Hi @andelopes, we will relay this guidance to the product design team and share any updates as they suggest since they place the final call on visual outputs. For now, I'm going to close this ticket since the initial issue was resolved. Thank you!
