### ISSUE TITLE
Utility shows up as "Component" on click

### ISSUE THREAD

**Issue by aayushpi** [twilio-labs/paste#61]
Steps to reproduce:
1. Open Utilities List: `https://paste.twilio.design/utilities`
2. Click on any utility. For example, `Text` in `https://paste.twilio.design/utilities`
3. You will see that the path changes to `https://paste.twilio.design/components/text` instead of staying in "Utilities"

Also, the page title shows up as "404"

**Comment by TheSisb** [comment]
Opened a PR https://github.com/twilio-labs/paste/pull/64 to fix this
