### ISSUE TITLE
Gutters prop in Grid creates token errors

### ISSUE THREAD

**Issue by alecnicolas** [twilio-labs/paste#617]
**Describe the bug**
When using the Gutters prop in Grid with spacing tokens, you get failed prop type errors.

**To Reproduce**
1. Set up a Grid and some columns
2. Apply the Gutters prop with one of the spacing tokens
3. Observe errors in browser console

**Expected behavior**
Nothing _breaks_ but the errors are there regardless.

**Screenshots**
![image](https://user-images.githubusercontent.com/29192545/88841798-508c6f80-d193-11ea-9862-59a4ba6a9a44.png)
![image](https://user-images.githubusercontent.com/29192545/88841720-32267400-d193-11ea-9354-2ec53af3e0b3.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: 84.0.4147.89

**Additional context**
Everything works fine but errors are printed out to console.
Seems like Grid passes the token strings as the actual margin value creating errors in the Box component which also expects tokens.

**Comment by richbachman** [comment]
Hi @alecnicolas, thanks for submitting this issue. I think this might be from an outdated version of Grid. We recently updated the package to fix this console error. The newest package version is `0.2.43`. If you update your package version and this is still and issue, let us know.

**Comment by alecnicolas** [comment]
> Hi @alecnicolas, thanks for submitting this issue. I think this might be from an outdated version of Grid. We recently updated the package to fix this console error. The newest package version is `0.2.43`. If you update your package version and this is still and issue, let us know.

Hey @richbachman! I updated @twilio-paste/core and Grid was updated as well. Looks like that error is gone but it was replaced with another.

![image](https://user-images.githubusercontent.com/29192545/88846739-e5469b80-d19a-11ea-82d6-42d28038860c.png)

**Comment by richbachman** [comment]
@alecnicolas apologies, I should have been more clear. With the core update you'll need to update the other Paste libraries as well. Here is a list of all the up to date packages: https://paste.twilio.design/getting-started/engineering/

We'll be working on a way to make keeping the packages in sync easier in the future.

**Comment by alecnicolas** [comment]
@richbachman Thanks for the clarification! Updating all the libraries fixed the issue, thanks.
