### ISSUE TITLE
Text component doesn't evaluate design tokens, but passes them directly to style

### ISSUE THREAD

**Issue by george-cz** [twilio-labs/paste#643]
**Describe the bug**
When using the `<Text />` component and adding a prop `fontSize` as mentioned in the docs (https://paste.twilio.design/primitives/text), the token is not evaluated but passed in the styles directly, leading up to this:

![Screenshot 2020-08-07 at 12 07 50](https://user-images.githubusercontent.com/2070479/89635306-13b52c80-d8a7-11ea-885b-c6c48291b31b.png)

When I try passing "14px" as the fontSize property, it works, but the library starts complaining:

`Warning: Failed prop type: [Text]: invalid prop supplied "fontSize=14px", expected a token value. See https://paste.twilio.design/tokens for available options.`

**To Reproduce**
1. Render a component: <Text fontSize="fontSize40">Hi</Text>
2. Observe the style generated

**Expected behavior**
Expected the token to be evaluated and replaced with rem value

**Desktop (please complete the following information):**
n/a

Version: @twilio-paste/text, 2.1.11

**Comment by george-cz** [comment]
Sorry, my bad, I wasn't wrapping the Text with `</CustomizationProvider>`. It works as expected.

**Comment by aayushpi** [comment]
Thanks for following up on this @george-cz!
