### ISSUE TITLE
Paste documentation website is not responsive

### ISSUE THREAD

**Issue by two24studios** [twilio-labs/paste#66]
The docs site experience on mobile is bad. The navigation takes up a majority of the screen, so it's almost impossible to read the content. We should add some responsive styles for the navigation and content so it's a better experience.

**Comment by TheSisb** [comment]
Copying my note from another issue: 
> We wanted to hold off on that part until more of the system is built so that we can build the website with our system. Specifically our layout components (grid & flex).  Marking this as blocked for now.

**Comment by aayushpi** [comment]
Moved to Backlog
