### ISSUE TITLE
Button component page needs the content wrapper

### ISSUE THREAD

**Issue by richbachman** [twilio-labs/paste#69]
The [button component page](https://paste.twilio.design/components/button) is missing the `content` wrapper so the content spans the full width of the site. See the [anchor page](https://paste.twilio.design/components/anchor) for comparison.

Button page screenshot:
![image](https://user-images.githubusercontent.com/1350081/63790171-fc5b7a00-c8b5-11e9-8730-d9ac8bc51272.png)

Anchor page screenshot for comparison:
![image](https://user-images.githubusercontent.com/1350081/63790193-0aa99600-c8b6-11e9-82d7-821f19d1d21a.png)

**Comment by wyze** [comment]
This looks like it has been fixed.

**Comment by SiTaggart** [comment]
It has yes. Closing
