### ISSUE TITLE
Tokens - Can it be used for SendGrid, Twilio and Flex?

### ISSUE THREAD

**Issue by JT1989** [twilio-labs/paste#73]
**Context**
The list of Tokens currently show values for SendGrid and Console. (this is mentioned on your Getting Started page: https://paste.twilio.design/getting-started/)

**Problem**
The Tokens page (https://paste.twilio.design/tokens) does not clearly communicate what the tokens can be used for. The Tokens page should show how tokens will show values for SendGrid and Console in a scannable way. 

For example, use a label that sends `SendGrid` and `Twilio Console` rather than explaining this in a sentence.

The end users of Paste might not read everything on your site and should not have to dig for this information. 

I strongly recommend placing information based on the topic and optimizing for quick scanning so that we can grok information quickly. 

**Rationale**
I've been sharing Paste 0.1 to my engineering team. The top question I hear: is this going to be used for SendGrid too?

**Comment by SiTaggart** [comment]
@JT1989 does the new theme switching on the site address this concern?

**Comment by serifluous** [comment]
Closing this with the addition of the theme switcher.
