### ISSUE TITLE
Tokens > Border Colors: Hard to see colors

### ISSUE THREAD

**Issue by JT1989** [twilio-labs/paste#74]
**Problem**
It's hard to see the tokens that we can use for *Border Colors* because it's showing the color in an itty bitty line. Similar colors are also shown next to each other.
<img width="1182" alt="Screen Shot 2019-08-28 at 11 00 20 AM" src="https://user-images.githubusercontent.com/8630856/63880757-2890fc80-c983-11e9-9dad-f2b2a623e8ee.png">

**Suggestion**
Show the border color _as a border_ by using the full height.
<img width="1099" alt="Screen Shot 2019-08-28 at 11 02 36 AM" src="https://user-images.githubusercontent.com/8630856/63881050-d7cdd380-c983-11e9-9424-b3d616f041bb.png">

**Example**
Salesforce Lightning System uses the full height to show the token for the border color - it's easy to see the colors that you can choose from.
<img width="798" alt="Screen Shot 2019-08-28 at 11 06 40 AM" src="https://user-images.githubusercontent.com/8630856/63881112-f633cf00-c983-11e9-8929-98cb56269586.png">

**Comment by ItsMeWithTheFace** [comment]
I'll work on this one
