### ISSUE TITLE
Buttons with the fullWidth prop don't center text

### ISSUE THREAD

**Issue by alecnicolas** [twilio-labs/paste#764]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
Buttons with the fullWidth prop aren't centering the text they wrap

**To Reproduce**
1. Create a button component that wraps some text
2. Add fullWidth prop

**Expected behavior**
The button should center the text but it does not.

**Screenshots**
<img width="269" alt="Screen Shot 2020-09-16 at 11 05 54 AM" src="https://user-images.githubusercontent.com/29192545/93376885-1f353500-f80f-11ea-8d90-673cf505579f.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: 84.0

**Comment by SiTaggart** [comment]
Hi @alecnicolas 

Thanks for the bug report, that definitely seems like a regression and a test case we're not covering. It's been added to the backlog for prioritization.

**Comment by richbachman** [comment]
Hi @alecnicolas 
We just merged this [PR](https://github.com/twilio-labs/paste/pull/797) which fixes the text centering for full width buttons. If you update to the latest version of core, you should see that fix. Let us know if you have any other issues.
