### ISSUE TITLE
@twilio-paste/combobox-primitive package.json doesn't match git commit and causes yarn check error

### ISSUE THREAD

**Issue by synnottd** [twilio-labs/paste#769]
**Describe the bug**
Seems like a package for `combobox-primitive` isn't being created correctly

**To Reproduce**
1. `yarn init`
2. `yarn add react react-dom prop-types react-uid`
3. `yarn add @twilio-paste/types @twilio-paste/style-props @twilio-paste/design-tokens @twilio-paste/theme @twilio-paste/icons @twilio-paste/styling-library @twilio-paste/animation-library @twilio-paste/dropdown-library @twilio-paste/reakit-library`
4. `yarn add @twilio-paste/core`
5. `yarn check`
(2-4 are from https://paste.twilio.design/getting-started/engineering/)

**Expected behavior**
No errors

**Error**
```
C02YW3Z1LVCJ:paste-test dsynnott$ yarn check
yarn check v1.21.0
error "@twilio-paste/core#@twilio-paste/combobox-primitive#@twilio-paste/dropdown-library@^0.1.2" doesn't satisfy found match of "@twilio-paste/dropdown-library@1.0.0"
error Found 1 errors.
```

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: chrome
 - Version: 84.0.4147.8

**Additional context**
`yarn.lock` for `@twilio-paste/combobox-primitive`
```
"@twilio-paste/combobox-primitive@^0.1.6":
  version "0.1.6"
  resolved "https://registry.yarnpkg.com/@twilio-paste/combobox-primitive/-/combobox-primitive-0.1.6.tgz#1440a1088953b7a5d1bf6a5b1c6c7ca2660193af"
  integrity sha512-3ULjVNVGLs/OZGk49TIwZCGGb0eq5FD+WhXGKpqVjOqWo96y3MOIc/CV9MgGZitw6hh3A4ZObyQtwQHo/ySgEQ==
```
`node_modules/@twilio-paste/combobox-primitive/package.json`
```
{
  "name": "@twilio-paste/combobox-primitive",
  "version": "0.1.6",
  "category": "user input",
  "status": "beta",
  "description": "An unstyled and accessible basis upon which to build a combobox.",
  "author": "Twilio Inc.",
  "license": "MIT",
  "main:dev": "src/index.tsx",
  "main": "dist/index.js",
  "module": "dist/index.es.js",
  "types": "dist/index.d.ts",
  "sideEffects": false,
  "publishConfig": {
    "access": "public"
  },
  "files": [
    "dist"
  ],
  "scripts": {
    "build": "yarn clean && yarn compile",
    "build:dev": "yarn clean && yarn compile:dev",
    "build:props": "typedoc --tsconfig ./tsconfig.json --json ./dist/prop-types.json",
    "clean": "rm -rf ./dist && rm -rf tsconfig.build.tsbuildinfo && rm -rf .rpt2_cache",
    "compile": "rollup -c --environment NODE_ENV:production",
    "compile:dev": "rollup -c --environment NODE_ENV:development",
    "prepublishOnly": "yarn build",
    "type-check": "tsc --noEmit"
  },
  "peerDependencies": {
    "@twilio-paste/dropdown-library": "^0.1.2",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
  "devDependencies": {
    "@twilio-paste/dropdown-library": "^1.0.0"
  },
  "gitHead": "2aabb2e458646aa9ca01fb3276090533563974db"
}
```
Commit mentioned in `package.json` above
https://github.com/twilio-labs/paste/commit/2aabb2e458646aa9ca01fb3276090533563974db#diff-25cd84a79296a045b1fd96b026d3cc39

Notice difference in ` "peerDependencies": { "@twilio-paste/dropdown-library": "^0.1.2" ... }`

**Comment by richbachman** [comment]
Hi @Daithi1. Thanks for posting the issue. We're taking a look at the issue and will update as soon as we can.

**Comment by Daithi1** [comment]
Thanks @richbachman, this isn't a blocker at all by the way. I just noticed by chance and thought I better report it.

**Comment by synnottd** [comment]
I can no longer reproduce.
