### ISSUE TITLE
getting started / design page is empty

### ISSUE THREAD

**Issue by myhlibovych** [twilio-labs/paste#771]
I came to Paste to read getting started for designers, and page https://paste.twilio.design/getting-started/design is empty.
 
Maybe it was never there, but I suppose it has to exist.

![image](https://user-images.githubusercontent.com/71466379/93522551-53594480-f93a-11ea-8daf-b0eee847373a.png)

**Comment by corinne-nagel** [comment]
Hey, welcome @myhlibovych 👋 We're actually working on an entirely new getting started page for designers so we'll be updating it here shortly. Thanks for letting us know!

**Comment by aayushpi** [comment]
This issue is now fixed. Thanks for reporting, @myhlibovych
