### ISSUE TITLE
"This project is maintained by the design systems team." dead link

### ISSUE THREAD

**Issue by sebm** [twilio-labs/paste#814]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
https://github.com/twilio-labs/paste/blob/main/README.md#maintainers links to https://github.com/orgs/twilio-labs/teams/design-systems, which 404s (at least, it does for me - ymmv)

**Comment by richbachman** [comment]
Hi @sebm. Thanks for pointing this out. Since the team page is part of Twilio-Labs, you might need team permissions to view that page. We'll look into it further.

**Comment by TheSisb** [comment]
Fixed in https://github.com/twilio-labs/paste/pull/1303
