### ISSUE TITLE
Dead or expired link on the avatar page

### ISSUE THREAD

**Issue by kevhealy-git** [twilio-labs/paste#816]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
Dead or expired link on the avatar page.

**To Reproduce**
1. Go to https://paste.twilio.design/components/avatar
2. Attempt to click on 'Paste Icon' link under 'About Avatar'
3. Takes you to a 404.

**Comment by serifluous** [comment]
Thanks for the catch, Kevin! Will be merging in a fix soon.
