### ISSUE TITLE
paste-core: latest version [2.16.61] is throwing error for Button and Anchor component

### ISSUE THREAD

**Issue by Kajal-Joshi** [twilio-labs/paste#827]
I tried to update paste to it's latest version, but after updating it I started getting following error for components like Button and Anchor etc. Please let me know if anyone has faced this issue!

**Errors :
For Button Component**
error TS2739: Type '{ children: Element; "data-test": string; variant: "primary" | "secondary"; size: "icon"; onClick: () => void; key: string; }' is missing the following properties from type 'Pick<ButtonProps, "contextMenu" | "dir" | "form" | "slot" | "style" | "title" | "children" | "placeholder" | "name" | "id" | "disabled" | "loading" | "as" | "href" | ... 257 more ... | "css">': translate, css

Sample Implementation for which got above error: 

    <Button variant="secondary" onClick={() => generateAndDownloadFile()}>
                    Download HTML file  
    </Button>

**For Anchor Component**
error TS2739: Type '{ children: string; href: string; }' is missing the following properties from type 'Pick<AnchorProps, "contextMenu" | "dir" | "slot" | "style" | "title" | "children" | "width" | "minWidth" | "maxWidth" | "height" | "minHeight" | "maxHeight" | "size" | ... 278 more ... | "referrerPolicy">': translate, css
     
Sample Implementation for which got above error: 

       <Anchor href={href}>
          {anchorText}
        </Anchor>

![image](https://user-images.githubusercontent.com/72342162/95178981-a9086a80-07dd-11eb-9f49-f693af61804d.png)

**Comment by SiTaggart** [comment]
hi @Kajal-Joshi, thanks for the report of the issue.

Can I ask some details about your environment? Could you list out what version of typescript and node you're running, also anything about the project, is it a Create React App project for example, something like that.

We've trying to replicate this locally and are struggling to get the same results.

Thanks

**Comment by Kajal-Joshi** [comment]
@SiTaggart sure!

From initial commit of project doesn't looks like it has been created using Create React App! Custom settings I guess.
**Details that could be helpful :**
**Versions:**
"typescript": "^3.9.5",
"@typescript-eslint/eslint-plugin": "^3.6.1",
"@typescript-eslint/parser": "^3.6.1"


**Eslint configuration :** 
module.exports = {
    extends: [
        'airbnb-typescript',
        'airbnb/hooks',
        'plugin:@typescript-eslint/recommended',
        'plugin:jest/recommended',
        'prettier',
        'prettier/react',
        'prettier/@typescript-eslint',
        'plugin:prettier/recommended'
    ],

    plugins: ['react', '@typescript-eslint', 'jest'],

    env: {
        browser: true,
        es6: true,
        jest: true
    },

    globals: {
        Atomics: 'readonly',
        SharedArrayBuffer: 'readonly'
    },

    parser: '@typescript-eslint/parser',

    parserOptions: {
        ecmaFeatures: {
            jsx: true
        },
        ecmaVersion: 2020,
        sourceType: 'module',
        project: './tsconfig.json'
    },

    settings: {
        'import/resolver': {
            alias: {
                map: [['#', './']]
            }
        }
    },

    rules: {
        'import/no-default-export': 'warn',
        'import/prefer-default-export': 'off',

        'default-case': 'off',
        'consistent-return': 'off',
        'import/no-extraneous-dependencies': 'off',
        'no-await-in-loop': 'off',
        'import/extensions': 'off',
        'import/no-cycle': 'off',

        'react/jsx-boolean-value': ['error', 'always'],

        'import/order': [
            'error',
            {
                groups: ['builtin', 'external', 'internal'],
                pathGroups: [
                    {
                        pattern: 'react',
                        group: 'external',
                        position: 'before'
                    },

                    {
                        pattern: '@console',
                        group: 'internal',
                        position: 'before'
                    },

                    {
                        pattern: '@twilio',
                        group: 'internal',
                        position: 'before'
                    },

                    {
                        pattern: '#/src/components/**',
                        group: 'internal',
                        position: 'before'
                    },

                    {
                        pattern: '#/src/common/components/**',
                        group: 'internal',
                        position: 'after'
                    },
                    {
                        pattern: '#/src/common/middleware/**',
                        group: 'internal',
                        position: 'after'
                    },
                    {
                        pattern: '#/src/common/models/**',
                        group: 'internal',
                        position: 'after'
                    },
                    {
                        pattern: '#/src/models/**',
                        group: 'internal',
                        position: 'after'
                    },

                    {
                        pattern: '#/__tests__/**',
                        group: 'internal',
                        position: 'after'
                    }
                ],
                pathGroupsExcludedImportTypes: ['react'],
                'newlines-between': 'always',
                alphabetize: {
                    order: 'asc',
                    caseInsensitive: true
                }
            }
        ],

        // TO BE FIXED:
        'react/destructuring-assignment': 'off',
        '@typescript-eslint/no-use-before-define': 'off',
        'no-param-reassign': 'off',
        '@typescript-eslint/no-unused-expressions': 'off',
        'no-prototype-builtins': 'off',
        'no-shadow': 'off',
        'react/prop-types': 'off',
        'no-useless-escape': 'off',
        'no-restricted-globals': 'off',
        'react-hooks/exhaustive-deps': 'off',
        '@typescript-eslint/ban-types': 'off',
        '@typescript-eslint/no-useless-constructor': 'off',
        'max-classes-per-file': 'off',
        'react-hooks/rules-of-hooks': 'off',
        'react/jsx-props-no-spreading': 'off',
        'react/no-array-index-key': 'off',
        'react/no-unescaped-entities': 'off',
        'no-return-assign': 'off',
        'no-underscore-dangle': 'off',
        'no-nested-ternary': 'off',
        'typescript-eslint/no-var-requires': 'off',
        'global-require': 'off',
        'react/no-render-return-value': 'off',
        'symbol-description': 'off',
        'no-case-declarations': 'off',
        '@typescript-eslint/naming-convention': 'off',
        'class-methods-use-this': 'off',
        'jest/valid-expect-in-promise': 'off',
        '@typescript-eslint/naming-convention': 'off',
        '@typescript-eslint/no-var-requires': 'off',
        'jsx-a11y/anchor-is-valid': 'off',
        'react/style-prop-object': 'off',
        'jsx-a11y/label-has-associated-control': 'off',
        'jsx-a11y/no-static-element-interactions': 'off',
        'jsx-a11y/click-events-have-key-events': 'off',
        'array-callback-return': 'off',
        'jest/valid-expect': 'off',
        'jest/no-identical-title': 'off',
        'prefer-destructuring': 'off'
    },

    overrides: [
        {
            files: ['**/*.tsx'],
            rules: {
                'react/prop-types': 'off'
            }
        }
    ]
};

**Comment by Daithi1** [comment]
I'm on the same team as Kajal, this was really  annoying me so spent some time on it. Turns out for whatever reason the `@types/testing-library__react`s version of `@types/react` was being used over the root level one. I think it is something to do with https://github.com/yarnpkg/yarn/issues/4489 (tldr: yarn handles `*` dependencies in an annoying way) although that is the opposite (wanting to use an older one). The version yarn and vscode were picking up was a bit older and didn't have `translate` on the `HTMLAttributes` declaration which `AnchorProps` (eventually) extends then 
```
declare const Anchor: React.ForwardRefExoticComponent<Pick<AnchorProps, "children" | ...  | "title" | "translate" | "radioGroup" | ...> & React.RefAttributes<HTMLAnchorElement>>;
```

Either way moral of the story `"**/@types/react": "16.9.44"` in `resolutions` fixed it.

**Comment by Daithi1** [comment]
Would it be possible to add the correct minimum version (the first with `css` and `translate`) of `@types/react` as a devDependency? This would probably prevent the possibility of this happening in the future.

**Comment by SiTaggart** [comment]
Hi @Daithi1, thanks for digging into that for us. We can certainly add that to the backlog to do in the coming sprint.

It was an odd one that we could see in a codesandbox, but no where else.

Just so I'm clear, is there a specific version to be _above_ or _below_? Or is it specific to `16.9.44` or `@types/react`?

**Comment by moyara** [comment]
Hi I also had issue with this.
I solved following https://github.com/emotion-js/emotion/issues/1431#issuecomment-529428305 with adding `import '@emotion/core';` at the top of my index.tsx

**Comment by SiTaggart** [comment]
We have just pushed an update to Paste which does seem to remedy the type issues for Button and Anchor. If you update your paste dependencies you should see this improve.

I'd also recommend following our new install guidelines which reduces your paste dependencies down to just 2 https://paste.twilio.design/getting-started/engineering#paste-packages

As for @moyara's issue with a css prop type error, I wouldn't recommend just importing emotion to resolve it. Emotion should be installed with Paste already. I feel like that is covering up something. Please update your deps and try without the import.

I'll close this for now. Let us know if it still causes an issue
