### ISSUE TITLE
Hierarchy & placement of components in relation to text

### ISSUE THREAD

**Issue by JT1989** [twilio-labs/paste#83]
There's a plethora of valuable, well-written documentation here. But, at first glance, the page looks quite overwhelming to read because it's dense and a TLDR-situation.

As a designer, I come here to quickly scan and find what we're looking for. I wish the information and components were displayed with better hierarchy and placement. 

I wish I could see the component  _in relation_ to the documentation. 

There's as lot of scrolling up and down to connect the dots. How might we improve the UX of this page so that information and components are shown contextually and with more visual organization?

<img width="1428" alt="Screen Shot 2019-09-05 at 4 33 42 PM" src="https://user-images.githubusercontent.com/8630856/64390890-777e0800-cffb-11e9-8b1c-8a1a49a632ef.png">

**Examples:**
Lightning Design System is visual, it's easy to scan and breaks up the information:
1. Component's Name
2. Best practices on how to use it & when not to use it.
3. Preview
4. Code

Overall, I can read best practices, see what the component looks like and show my engineers the code they can use. It's also super easy to copy and paste the component, to boot! 

I don't have to parse through each line of code to find the component that I'm looking for. 

I don't have to scroll up and down to find things. I don't have to scroll up and down to connect the dots on what a primary button looks like and when to use it. 

<img width="861" alt="Screen Shot 2019-09-05 at 4 42 49 PM" src="https://user-images.githubusercontent.com/8630856/64391081-376b5500-cffc-11e9-9913-24322a411868.png">

**Comment by SiTaggart** [comment]
Thanks for this great feedback!

I agree I think it is a bit text-heavy and could do with an example for each variant, within direct context to the documentation on that variant. Thanks for providing a reference example too, I happen to think (although with some heavy bias) the Lightning Design System does a pretty good job on that respect and we could do something super similar.

We'll discuss it as a team and let you know how and when we plan to make that change.

**Comment by SiTaggart** [comment]
Does this look better to you @JT1989? 

https://paste-git-feat-button-docs.twilio-dsys.now.sh/components/button

**Comment by SiTaggart** [comment]
Closing based on the updates I made. If you don't think they address your feedback, please re-open the issue.

**Comment by JT1989** [comment]
Absolutely, you've addressed the feedback spectacularly! Thanks Simon! 

I have a heavy bias towards Lightning Design system too - I usually go to Polaris or Lightning Design System as the role models of design systems =D

**Comment by JT1989** [comment]
Also, noticed y'all cleaned up the spacing/padding, nice work!
