### ISSUE TITLE
Spelling mistake in Table component docs for importing the component

### ISSUE THREAD

**Issue by PoojMenon** [twilio-labs/paste#856]
**Describe the bug**
Spelling mistake in the package name when importing a table in the sample code.

**To Reproduce**
1. Go to https://paste.twilio.design/components/table/#usage
2. Copy the import statement for Table
`import {Table} from ‘@twliio-paste/table’;
`

**Expected behavior**
Should be able to use the Table component. However, it is not imported successfully due to the spelling mistakes. Shamefully, took me a few minutes to see the spelling error. 

**Screenshots**
![image](https://user-images.githubusercontent.com/72031986/96139090-6427b680-0ef6-11eb-9e01-a901f8e4f91d.png)

**Comment by richbachman** [comment]
Hi @PoojMenon 
Thanks for catching this. We'll get it fixed asap.
