### ISSUE TITLE
"How to Add an Icon" dead link

### ISSUE THREAD

**Issue by cfree** [twilio-labs/paste#894]
**Describe the bug**
paste-icons README has a dead link to documentation on how to add a new icon

**To Reproduce**
1. Visit [paste-icons README](https://github.com/twilio-labs/paste/tree/main/packages/paste-icons)
2. Scroll to [Adding new icons section](https://github.com/twilio-labs/paste/tree/main/packages/paste-icons#adding-new-icons)
3. Click [review our documentation](https://paste.twilio.design/icon-system/how-to-add-an-icon/#exporting-and-adding-the-icon)
4. Link goes to 404 page

**Expected behavior**
Link goes to [actual page](https://paste.twilio.design/icons/how-to-add-an-icon)

**Desktop (please complete the following information):**
All

PR: #895

**Comment by richbachman** [comment]
Hi @cfree.

Good catch. We'll get that fixed. Glad you found the actual page you were looking for.

**Comment by cfree** [comment]
@richbachman Here's a PR, if you'd like: #895

**Comment by TheSisb** [comment]
Thanks for the PR! Merged 👍
