### ISSUE TITLE
Input inline error icon size is changing

### ISSUE THREAD

**Issue by Dooffy** [twilio-labs/paste#972]
**Describe the bug**
Input inline error icon size is relative and depends on error message length.

**To Reproduce**
1. Create new input element with multi-line error message.

**Expected behavior**
Icon size should not change.

**Screenshots**
<img width="803" alt="Screenshot 2020-11-25 at 11 43 07" src="https://user-images.githubusercontent.com/1443584/100224848-47c76280-2f15-11eb-9b98-ef17b564c6c8.png">

**Comment by SiTaggart** [comment]
Thanks for the bug report @Dooffy. I've created a ticket in our backlog to address as soon as possible.

**Comment by richbachman** [comment]
Hi @Dooffy. We just merged a fix in for this. You'll need to update your Paste dependencies once the build is finished. Let us know if you have any other issues.
