### ISSUE TITLE
Sketch friendly values for tokens

### ISSUE THREAD

**Issue by seanmateer** [twilio-labs/paste#98]
**Problem**
While working in Sketch, I find myself often referring to https://paste.twilio.design/tokens to confirm font-size or spacing sizes. Because these values are in rems, I have to either do mental math or inspect element to get a pixel size out to use in Sketch. 

**Suggestion**
There may be plugins that allow you to use rems in Sketch, but in the spirit of not requiring Sketch plugins, It would be nice to consider also including pixel values here, or perhaps a way to hover and get a pixel reference.

**Comment by seanmateer** [comment]
Re: doing mental math above - I find that I expect that doubling a token value should double the pixel/rem value consistently. I.E. $space-10 (0.125) to $space-20 (0.25) doubles as I would expect, but $space-100(2.25) to $space-200 (4.75) does not. This may be less of a problem if there were pixel values to refer to, but causes some confusion for me.

**Comment by serifluous** [comment]
Thanks, Sean! It's been added to our backlog.

**Comment by SiTaggart** [comment]
Hi @seanmateer @Angelangg and @pguptaDS

Does this do an good enough job of solving this issue? https://paste-git-feat-websitefriendly-token-values.twilio-dsys.now.sh/tokens/

**Comment by pguptaDS** [comment]
Yes, this is great! Thank you.

**Comment by seanmateer** [comment]
Looks good, thanks for adding @SiTaggart!
